import test from 'node:test';
import assert from 'node:assert/strict';
import {AdminService} from '../src/admin-service.ts';
import {DomainError,PlatformService} from '../src/domain.ts';

test('백오피스 대시보드는 귀속·원장·정산·파트너·감사를 한 번에 제공한다',()=>{const platform=new PlatformService(),dashboard=new AdminService(platform).dashboard();assert.equal(dashboard.member.id,'M-1029');assert.equal(dashboard.ledger.length,4);assert.equal(dashboard.settlement.id,'S-2026-09-A');assert.equal(dashboard.partner.id,'P-A')});
test('귀속 변경 요청은 요청자와 다른 슈퍼관리자만 반려한다',()=>{const platform=new PlatformService(),admin=new AdminService(platform),request=platform.requestAttributionChange({memberId:'M-1029',targetCode:'RS-B002-SEO',effectiveFrom:'2026-10-01T00:00:00+09:00',reason:'권역 변경'},'operator01','OPERATOR');assert.throws(()=>admin.rejectAttribution(request.id,'동일 요청자','operator01','SUPER_ADMIN'),(error:DomainError)=>error.code==='SEGREGATION_OF_DUTIES');assert.equal(admin.rejectAttribution(request.id,'증빙 부족','super01','SUPER_ADMIN').status,'REJECTED')});
test('분쟁 HOLD는 개별 건에만 적용되고 슈퍼관리자가 해제한다',()=>{const platform=new PlatformService();platform.holdDispute('O-260901','operator01');assert.equal([...platform.db.ledger.values()].find(item=>item.transactionId==='O-260901')?.status,'HOLD');assert.equal([...platform.db.ledger.values()].find(item=>item.transactionId==='O-260905')?.status,'READY');assert.throws(()=>platform.releaseDispute('O-260901','operator01','OPERATOR'),(error:DomainError)=>error.code==='FORBIDDEN');assert.equal(platform.releaseDispute('O-260901','super01','SUPER_ADMIN').status,'READY')});
test('세금계산서와 재검증 게이트를 통과해야 지급한다',()=>{const platform=new PlatformService();platform.finalizeSettlement('S-2026-09-A');platform.markTaxError('S-2026-09-A','사업자정보 불일치','operator01');assert.throws(()=>platform.paySettlement('S-2026-09-A','super01','SUPER_ADMIN'),(error:DomainError)=>error.code==='SETTLEMENT_NOT_PAYABLE');platform.verifyTax('S-2026-09-A','operator01');platform.startPartnerReview('P-A','ANNUAL','operator01');assert.throws(()=>platform.paySettlement('S-2026-09-A','super01','SUPER_ADMIN'),(error:DomainError)=>error.code==='PARTNER_PAYOUT_HELD');platform.completePartnerReview('P-A','super01','SUPER_ADMIN');assert.equal(platform.paySettlement('S-2026-09-A','super01','SUPER_ADMIN').status,'PAID')});
test('쿠폰 캠페인은 생성·중지·복원 이력을 보존한다',()=>{const platform=new PlatformService(),admin=new AdminService(platform);assert.equal(admin.createCoupon({code:' cafe10 ',target:'카페 회원',benefit:'10%'},'operator01').code,'CAFE10');assert.throws(()=>admin.suspendCoupon('CAFE10','종료','operator01','OPERATOR'),(error:DomainError)=>error.code==='FORBIDDEN');assert.equal(admin.suspendCoupon('CAFE10','프로모션 종료','super01','SUPER_ADMIN').status,'SUSPENDED');assert.equal(admin.restoreCoupon('CAFE10','super01','SUPER_ADMIN').status,'ACTIVE');assert.equal(platform.db.audit[0].action,'COUPON_CAMPAIGN_RESTORED')});
