import test from 'node:test';
import assert from 'node:assert/strict';
import {PlatformService} from '../src/domain.ts';
import {BackofficeService} from '../src/backoffice-service.ts';

const setup=()=>{const platform=new PlatformService();return{platform,ops:new BackofficeService(platform)}};

test('전체 관리자 모듈과 통합 대시보드를 제공한다',()=>{const {ops}=setup();assert.equal(ops.modules().length,16);const dashboard=ops.dashboard();assert.equal(dashboard.kpis.orders,1);assert.equal(dashboard.newEstimates.length,1);assert.ok(dashboard.partnerTop.length>=2)});

test('추천코드 변경 이력과 소급 승인 권한을 보존한다',()=>{const {ops}=setup();const referral=ops.create('referrals',{code:'RS-A001-PARK',partnerId:'P-A',ownerId:'PARK',commissionRule:{rate:.08}},'md01');assert.equal(referral.status,'ACTIVE');assert.throws(()=>ops.update('referrals',referral.id,{commissionRule:{rate:.09},effectiveFrom:'2026-10-01',reason:'정책 변경',retroactive:true},'md01','MD'),(error:any)=>error.code==='FORBIDDEN');const updated=ops.update('referrals',referral.id,{commissionRule:{rate:.09},effectiveFrom:'2026-10-01',reason:'정책 변경',retroactive:false},'md01','MD');assert.equal((updated.history as unknown[]).length,1)});

test('캠페인과 회원 쿠폰을 분리하고 중지·삭제 이력을 유지한다',()=>{const {ops}=setup();assert.throws(()=>ops.create('coupons',{code:'RATE10',discountType:'PERCENT',discountValue:10,maxDiscount:0},'md01'),(error:any)=>error.code==='MAX_DISCOUNT_REQUIRED');const campaign=ops.create('coupons',{code:'RATE10',title:'10% 할인',discountType:'PERCENT',discountValue:10,maxDiscount:50000,minimumAmount:100000,startsAt:'2026-09-01',endsAt:'2026-12-31',partnerId:'P-A'},'md01');ops.transition('coupons',campaign.id,'ACTIVE','md01');const issued=ops.issueMemberCoupon('M-1029',campaign.id,'2026-11-30','md01');assert.equal(issued.kind,'MEMBER');assert.throws(()=>ops.issueMemberCoupon('M-1029',campaign.id,'2026-11-30','md01'),(error:any)=>error.code==='COUPON_ALREADY_ISSUED');assert.throws(()=>ops.suspendCoupon(campaign.id,'긴급 중지',true,'md01','MD'),(error:any)=>error.code==='FORBIDDEN');assert.equal(ops.suspendCoupon(campaign.id,'긴급 중지',true,'super01','SUPER_ADMIN').suspendedMembers,1);assert.equal(ops.deleteCoupon(campaign.id,'프로모션 종료','super01','SUPER_ADMIN').status,'REVOKED')});

test('RF-01 추천코드 개편 시 이전 코드를 alias로 보존해 계속 검증된다',()=>{const {platform,ops}=setup();ops.update('referrals','RS-A001-KIM',{code:'RS-A001-NEW',reason:'코드 체계 개편',effectiveFrom:'2026-10-01'},'super01','SUPER_ADMIN');assert.equal(platform.validateReferral('RS-A001-NEW').ownerId,'KIM');assert.equal(platform.validateReferral('rs-a001-kim').ownerId,'KIM')});

test('상품 등록·SKU 조합 생성·상태 전이를 관리한다',()=>{const {ops}=setup();const product=ops.create('products',{code:'SO-100',name:'소파',regularPrice:900000,salePrice:800000,costPrice:500000,options:{색상:['Black','Ivory'],사이즈:['2P','3P']}},'md01');const generated=ops.generateSkus(product.id,'md01');assert.equal(generated.count,4);assert.equal(ops.transition('products',product.id,'ACTIVE','md01').status,'ACTIVE');assert.throws(()=>ops.transition('products',product.id,'DRAFT','md01'),(error:any)=>error.code==='INVALID_STATUS_TRANSITION')});

test('상품 등록·수정 시 코드 중복·역가격을 차단하고 수정 재검증한다',()=>{const {ops}=setup();assert.throws(()=>ops.create('products',{code:'CH-102',name:'중복',regularPrice:1000,salePrice:900},'md01'),(e:any)=>e.code==='PRODUCT_CODE_DUPLICATED');assert.throws(()=>ops.create('products',{code:'NEW-1',name:'역가격',regularPrice:1000,salePrice:2000},'md01'),(e:any)=>e.code==='INVALID_PRICE');const product=ops.create('products',{code:'ok-1',name:'정상',regularPrice:1000,salePrice:900},'md01');assert.equal(product.code,'OK-1');assert.ok(Array.isArray(product.images));assert.throws(()=>ops.update('products',product.id,{salePrice:5000},'md01'),(e:any)=>e.code==='INVALID_PRICE');assert.throws(()=>ops.update('products',product.id,{code:'CH-102'},'md01'),(e:any)=>e.code==='PRODUCT_CODE_DUPLICATED');assert.equal(ops.update('products',product.id,{salePrice:800,images:['/uploads/a.png']},'md01').salePrice,800)});

test('상품 카테고리는 표준값만 허용하고 목록을 카테고리로 필터한다',()=>{const {ops}=setup();
 assert.throws(()=>ops.create('products',{code:'CAT-BAD',name:'자유입력',regularPrice:1000,salePrice:900,category:'의자'},'md01'),(e:any)=>e.code==='INVALID_CATEGORY');
 const p=ops.create('products',{code:'LMP-1',name:'플로어 램프',regularPrice:1000,salePrice:900,category:'조명'},'md01');
 assert.equal(p.category,'조명');
 assert.equal(ops.list('products',{category:'조명'}).items.length,1);
 assert.equal(ops.list('products',{category:'조명'}).items[0].code,'LMP-1');
 assert.ok(ops.list('products',{category:'우드 체어'}).items.some(x=>x.code==='CH-102'));
 assert.throws(()=>ops.update('products',p.id,{category:'없는분류'},'md01'),(e:any)=>e.code==='INVALID_CATEGORY')});

test('쇼케이스 등록 검증과 공개 전 이미지 필수를 강제한다',()=>{const {ops}=setup();assert.throws(()=>ops.create('showcases',{partnerId:'P-A'},'md01'),(e:any)=>e.code==='VALIDATION_ERROR');assert.throws(()=>ops.create('showcases',{title:'미소속',partnerId:'P-XXX'},'md01'),(e:any)=>e.code==='RESOURCE_NOT_FOUND');const draft=ops.create('showcases',{title:'신규 쇼케이스',partnerId:'P-A'},'md01');assert.equal(draft.status,'DRAFT');assert.ok(Array.isArray(draft.hotspots));assert.throws(()=>ops.transition('showcases',draft.id,'PUBLISHED','md01'),(e:any)=>e.code==='SHOWCASE_IMAGE_REQUIRED');ops.update('showcases',draft.id,{imageUrl:'/uploads/cafe.png'},'md01');assert.equal(ops.transition('showcases',draft.id,'PUBLISHED','md01').status,'PUBLISHED')});

test('스토어프론트 공개 API는 공개 항목만·민감필드 제외로 노출한다',()=>{const {ops}=setup();
 const products=ops.storefrontProducts();assert.ok(products.items.length>=1);assert.ok(products.items.every(p=>p.status==='ACTIVE'));assert.ok(products.items.every(p=>!('costPrice' in p)));
 const showcases=ops.storefrontShowcases();assert.ok(showcases.items.every(s=>s.status==='PUBLISHED'));assert.equal(showcases.items.find(s=>s.id==='SHO-100')?.title,'성수 Natural Cafe');
 const detail=ops.storefrontShowcase('SHO-100');assert.equal(detail.hotspots.length,2);assert.equal(detail.hotspots[0].product.name,'우드 체어');assert.ok(!('costPrice' in detail.hotspots[0].product));
 const product=ops.storefrontProduct('PRD-101');assert.equal(product.name,'우드 체어');assert.ok(product.showcases.some(s=>s.id==='SHO-100'));
 const draft=ops.create('products',{code:'HID-1',name:'숨김상품',regularPrice:1000,salePrice:900},'md01');assert.throws(()=>ops.storefrontProduct(draft.id),(e:any)=>e.code==='RESOURCE_NOT_FOUND')});

test('재고 조정은 음수재고를 차단하고 안전재고 상태를 계산한다',()=>{const {ops}=setup();assert.equal(ops.adjustInventory('CH-102-N',-30,'실사 조정','md01').status,'LOW');assert.throws(()=>ops.adjustInventory('CH-102-N',-30,'과다 차감','md01'),(error:any)=>error.code==='NEGATIVE_INVENTORY');assert.equal(ops.adjustInventory('CH-102-N',10,'입고','md01','RECEIPT').status,'NORMAL')});

test('쇼케이스 Hotspot은 실제 상품과 백분율 좌표만 연결한다',()=>{const {ops}=setup();const result=ops.setHotspots('SHO-100',[{productId:'PRD-201',x:25.5,y:72}],'md01');assert.equal((result.hotspots as unknown[]).length,1);assert.throws(()=>ops.setHotspots('SHO-100',[{productId:'PRD-201',x:120,y:2}],'md01'),(error:any)=>error.code==='INVALID_HOTSPOT_POSITION')});

test('주문 배송과 클레임 환불은 상태·PG·정산 조정을 함께 검증한다',()=>{const {ops}=setup();const shipped=ops.registerShipment('O-0291',{carrier:'CJ',trackingNumber:'123456'},'cs01');assert.equal(shipped.shippingStatus,'SHIPPED');const claim=ops.inspectClaim('C-102',{result:'정상 / 재판매 가능',resellable:true,refundRequired:true},'cs01');assert.equal(claim.status,'REFUND_PENDING');assert.throws(()=>ops.approveRefund('C-102',{amount:358000,returnFee:30000,pgSucceeded:false},'finance01','FINANCE'),(error:any)=>error.code==='PG_REFUND_NOT_CONFIRMED');const approved=ops.approveRefund('C-102',{amount:358000,returnFee:30000,pgSucceeded:true,pgReference:'PG-1',fullCancellation:false},'finance01','FINANCE');assert.equal(approved.claim.status,'REFUNDED');assert.equal(approved.claim.couponResolution,'KEEP_USED');assert.equal(approved.claim.settlementApplied,true)});

test('견적 Revision과 렌탈 계약·상태 Workflow를 보존한다',()=>{const {ops}=setup();assert.equal(ops.assignEstimate('E-0104','md01','2026-09-20','cs01').status,'ASSIGNED');const revision=ops.saveRevision('E-0104',{items:[{productId:'PRD-101',quantity:4,unitPrice:150000,discount:20000}],shipping:50000,installation:100000,construction:300000},'md01');assert.equal(revision.version,1);assert.equal(revision.total,1030000);assert.equal(ops.transition('estimates','E-0104','PROPOSED','md01').status,'PROPOSED');const rental=ops.uploadRentalContract('R-0104',{url:'https://files.example/R-0104.pdf',fileName:'계약서.pdf'},'cs01');assert.equal((rental.documents as unknown[]).length,1);assert.equal(ops.transition('rentals','R-0104','CONTRACTED','cs01').status,'CONTRACTED')});

test('회원 메모·강제 쿠폰과 콘텐츠 노출 기간을 검증한다',()=>{const {ops}=setup();const memo=ops.addMemberMemo('M-1029','다음 주 상담 예정','cs01');assert.equal(memo.actor,'cs01');const coupon=ops.forceMemberCoupon('M-1029','PARTNERA10','2026-11-30T14:59:59.000Z','admin01');assert.equal(coupon.memberId,'M-1029');assert.throws(()=>ops.create('contents',{title:'잘못된 기간',startsAt:'2026-10-02',endsAt:'2026-10-01'},'md01'),(error:any)=>error.code==='INVALID_CONTENT_PERIOD')});

test('알림 자동화는 멱등키로 채널별 발송을 한 번만 예약한다',()=>{const {ops}=setup();const first=ops.dispatchNotification('MEMBER_SIGNUP','M-1029',{coupon:'WELCOME50'},'signup:M-1029','system');assert.equal(first.duplicate,false);assert.equal(first.deliveries.length,2);const again=ops.dispatchNotification('MEMBER_SIGNUP','M-1029',{coupon:'WELCOME50'},'signup:M-1029','system');assert.equal(again.duplicate,true);assert.equal(again.deliveries.length,1)});

test('Role Matrix와 Partner 소유 범위를 강제한다',()=>{const {ops}=setup();ops.authorize('MD','products','write');assert.throws(()=>ops.authorize('MD','orders','write'),(error:any)=>error.code==='FORBIDDEN');assert.equal(ops.assertPartnerScope('orders','O-0291','P-A').id,'O-0291');assert.throws(()=>ops.assertPartnerScope('orders','O-0291','P-B'),(error:any)=>error.code==='FORBIDDEN')});

test('정산 확정 잠금·직무분리·API Key·연동 재처리를 감사한다',()=>{const {platform,ops}=setup();const settlement=ops.recalculateSettlement('SET-2026-09-A','finance01');assert.equal(settlement.commission,2408000);assert.throws(()=>ops.confirmSettlement('SET-2026-09-A',2408000,'finance01','FINANCE'),(error:any)=>error.code==='SEGREGATION_OF_DUTIES');assert.throws(()=>ops.confirmSettlement('SET-2026-09-A',1,'super01','SUPER_ADMIN'),(error:any)=>error.code==='SETTLEMENT_AMOUNT_MISMATCH');assert.equal(ops.confirmSettlement('SET-2026-09-A',2408000,'super01','SUPER_ADMIN').locked,true);assert.throws(()=>ops.update('settlements','SET-2026-09-A',{refunds:0},'finance01'),(error:any)=>error.code==='SETTLEMENT_LOCKED');const key=ops.rotateApiKey('P-A','super01','SUPER_ADMIN');assert.match(key.apiKey,/^pk_live_/);assert.equal(key.shownOnce,true);assert.throws(()=>ops.updateRole('MD',['*'],'md01','MD'),(error:any)=>error.code==='FORBIDDEN');assert.deepEqual(ops.updateRole('MD',['products:write'],'super01','SUPER_ADMIN').permissions,['products:write']);assert.equal(ops.reprocessIntegration('INT-PARTNER','super01').status,'QUEUED');assert.ok(platform.db.audit.length>=5)});

test('목록 CSV·대량 상태변경과 고객 API 정책 동기화를 제공한다',()=>{const {platform,ops}=setup();const one=ops.create('products',{code:'BL-1',name:'벌크 1',regularPrice:10,salePrice:9},'md01'),two=ops.create('products',{code:'BL-2',name:'벌크 2',regularPrice:10,salePrice:9},'md01');assert.equal(ops.bulkTransition('products',[one.id,two.id],'ACTIVE','md01').count,2);const exported=ops.exportRows('products',{status:'ACTIVE'});assert.equal(exported.mimeType,'text/csv; charset=utf-8');assert.match(exported.content,/BL-1/);const referral=ops.create('referrals',{code:'RS-A001-LEE',partnerId:'P-A',ownerId:'LEE'},'md01');assert.equal(platform.validateReferral('rs-a001-lee').ownerId,'LEE');ops.transition('referrals',referral.id,'SUSPENDED','md01');assert.throws(()=>platform.validateReferral('RS-A001-LEE'),(error:any)=>error.code==='REFERRAL_SUSPENDED');const campaign=ops.create('coupons',{code:'SYNC5000',title:'연동 할인',discountType:'FIXED',discountValue:5000,minimumAmount:20000,startsAt:'2026-01-01',endsAt:'2026-12-31T23:59:59.999Z'},'md01');ops.transition('coupons',campaign.id,'ACTIVE','md01');const coupon=platform.registerCoupon('M-SYNC','SYNC5000');assert.equal(coupon.amount,5000);assert.equal(coupon.minAmount,20000)});

test('정률 쿠폰은 적격금액에 할인율과 최대한도를 적용한다',()=>{const {platform}=setup();const coupon=platform.registerCoupon('M-RATE','PARTNERA10');assert.equal(coupon.discountType,'PERCENT');assert.equal(coupon.amount,0);const reserved=platform.reserveCoupon(coupon.id,'M-RATE',780000,'RATE-RESERVE');assert.equal(reserved.discountAmount,78000)});
