import test from 'node:test';import assert from 'node:assert/strict';
import {BusinessCalendar,isoDate} from '../src/infrastructure/business-calendar.ts';import {SettlementScheduler} from '../src/infrastructure/scheduler.ts';import {OutboxPublisher} from '../src/infrastructure/outbox.ts';import type {Database} from '../src/infrastructure/database.ts';

class FakeDatabase implements Database{mode='memory' as const;calls:{text:string;params?:unknown[]}[]=[];responses:any[][]=[];async health(){return true}async close(){}async withTransaction<T>(work:(q:(text:string,params?:unknown[])=>Promise<{rows:any[]}>)=>Promise<T>){return work(async(text,params)=>{this.calls.push({text,params});return{rows:this.responses.shift()||[]}})}}

test('27일이 주말이면 직전 영업일로 지급일을 계산한다',()=>{const calendar=new BusinessCalendar();assert.equal(isoDate(calendar.paymentDate(2026,5)),'2026-06-26')});
test('대한민국 공휴일을 제외하고 세금계산서 3영업일 전을 계산한다',()=>{const calendar=new BusinessCalendar(['2026-10-26']);const scheduled=calendar.paymentDate(2026,9),taxDue=calendar.addBusinessDays(scheduled,-3);assert.equal(isoDate(scheduled),'2026-10-27');assert.equal(isoDate(taxDue),'2026-10-21')});
test('스케줄러는 이의기간 종료 건과 지급 가능 건만 갱신한다',async()=>{const db=new FakeDatabase();db.responses=[[{id:'S-FINAL'}],[{id:'S-PAID'}]];const result=await new SettlementScheduler(db,new BusinessCalendar()).run(new Date('2026-10-27T00:00:00Z'));assert.deepEqual(result,{finalized:['S-FINAL'],paid:['S-PAID']});assert.match(db.calls[1].text,/p\.payout_hold=false/)});
test('Outbox 성공 건을 발행 완료 처리한다',async()=>{const db=new FakeDatabase();db.responses=[[{id:'E1',topic:'commission.paid',payload:{id:'S1'}}],[]];const sent:any[]=[];const result=await new OutboxPublisher(db,async(topic,payload)=>{sent.push({topic,payload})}).flush();assert.deepEqual(result,{published:['E1'],failed:[]});assert.equal(sent[0].topic,'commission.paid');assert.match(db.calls[1].text,/published_at=now/)});
test('Outbox 실패 건은 지수 백오프로 재시도 예약한다',async()=>{const db=new FakeDatabase();db.responses=[[{id:'E2',topic:'commission.paid',payload:{id:'S2'}}],[]];const result=await new OutboxPublisher(db,async()=>{throw new Error('network')}).flush();assert.deepEqual(result,{published:[],failed:['E2']});assert.match(db.calls[1].text,/next_attempt_at/)});
