CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE partner_status AS ENUM ('ACTIVE','REVIEW','ENDED');
CREATE TYPE coupon_status AS ENUM ('DRAFT','ISSUED','RESERVED','USED','SUSPENDED','EXPIRED','REVOKED');
CREATE TYPE ledger_status AS ENUM ('READY','HOLD','PAID','CANCELLED');

CREATE TABLE partners (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, name text NOT NULL, status partner_status NOT NULL DEFAULT 'REVIEW', payout_hold boolean NOT NULL DEFAULT true, last_verified_at timestamptz, ended_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE referral_codes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), canonical_code text UNIQUE NOT NULL CHECK (canonical_code = upper(trim(canonical_code))), partner_id uuid NOT NULL REFERENCES partners(id), owner_code text NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','SUSPENDED','EXPIRED')), expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE referral_aliases (alias_code text PRIMARY KEY, referral_code_id uuid NOT NULL REFERENCES referral_codes(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, first_referral_code_id uuid NOT NULL REFERENCES referral_codes(id), current_referral_code_id uuid NOT NULL REFERENCES referral_codes(id), current_effective_from timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE attribution_change_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES members(id), before_referral_code_id uuid NOT NULL REFERENCES referral_codes(id), after_referral_code_id uuid NOT NULL REFERENCES referral_codes(id), effective_from timestamptz NOT NULL, reason text NOT NULL, retroactive boolean NOT NULL DEFAULT false, status text NOT NULL CHECK(status IN ('PENDING','APPROVED','REJECTED')), requested_by text NOT NULL, approved_by text, created_at timestamptz NOT NULL DEFAULT now(), approved_at timestamptz, CHECK (approved_by IS NULL OR approved_by <> requested_by));
CREATE TABLE coupon_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text UNIQUE NOT NULL, partner_id uuid REFERENCES partners(id), title text NOT NULL, amount_krw bigint NOT NULL CHECK(amount_krw>=0), minimum_krw bigint NOT NULL DEFAULT 0, status text NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, purchase_enabled boolean NOT NULL DEFAULT true, rental_enabled boolean NOT NULL DEFAULT false, max_discount_krw bigint, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE member_coupons (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), member_id uuid NOT NULL REFERENCES members(id), campaign_id uuid NOT NULL REFERENCES coupon_campaigns(id), status coupon_status NOT NULL DEFAULT 'ISSUED', expires_at timestamptz NOT NULL, reservation_id text, reserved_at timestamptz, used_at timestamptz, source_coupon_id uuid REFERENCES member_coupons(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(member_id,campaign_id));
CREATE TABLE commission_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), partner_id uuid NOT NULL REFERENCES partners(id), period date NOT NULL, transaction_id text NOT NULL, kind text NOT NULL CHECK(kind IN ('PURCHASE','RENTAL_UPFRONT','RENTAL_FINAL','NEGATIVE')), amount_krw bigint NOT NULL, status ledger_status NOT NULL DEFAULT 'READY', hold_reason text, source_ledger_id uuid REFERENCES commission_ledger(id), calculation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(transaction_id,kind));
CREATE TABLE settlements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), partner_id uuid NOT NULL REFERENCES partners(id), period date NOT NULL, status text NOT NULL CHECK(status IN ('REVIEW','FINAL','HELD','SPECIAL_PAY','PAID')), dispute_window text NOT NULL CHECK(dispute_window IN ('OPEN','CLOSED')), tax_status text NOT NULL CHECK(tax_status IN ('MISSING','ERROR','VERIFIED')), hold_reason text, statement_issued_at timestamptz, dispute_due_at timestamptz, scheduled_pay_date date, paid_at timestamptz, UNIQUE(partner_id,period));
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text NOT NULL, entity_id text NOT NULL, action text NOT NULL, before_data jsonb, after_data jsonb, reason text, requested_by text, approved_by text, actor_id text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), source_ip inet, correlation_id text, idempotency_key text UNIQUE);
CREATE INDEX commission_ledger_partner_period_idx ON commission_ledger(partner_id,period,status);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type,entity_id,occurred_at DESC);
