import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../../prototype/member-auth.js',import.meta.url),'utf8');
const tick=async()=>{for(let i=0;i<4;i++)await new Promise(resolve=>setImmediate(resolve));};
function setup(mode:string,mustChangePassword=false){
 const saved=new Map<string,string>(),button:any={disabled:false},form:any={hidden:false,querySelector:()=>button};
 const nodes:any={};for(const name of ['memberEmail','memberPassword','memberPasswordConfirm','memberName','memberPhone','referralCode','termsConsent','privacyConsent','emailCode','sendVerification','verifyEmail','verifyReferral','emailStatus','referralResult','memberAuthStatus','memberRecovery','temporaryPassword','newMemberPassword','confirmMemberPassword','memberPasswordStatus'])nodes['#'+name]={value:'',checked:true,reportValidity:()=>true,textContent:''};
 Object.assign(nodes['#memberEmail'],{value:'member@example.com'});nodes['#memberPassword'].value=nodes['#memberPasswordConfirm'].value='Pass123!';nodes['#memberPhone'].value='01012345678';nodes['#emailCode'].value='123456';
 nodes['#memberSignupForm']=mode==='signup'?form:null;nodes['#memberLoginForm']=mode==='login'?form:null;nodes['#memberPasswordForm']={hidden:true,querySelector:()=>button,reset(){}};
 const replacements:string[]=[],requests:any[]=[],location:any={search:'',replace:(url:string)=>replacements.push(url)};
 runInNewContext(source,{document:{querySelector:(q:string)=>nodes[q]||null,querySelectorAll:()=>[]},window:{G9STAR:{apiBase:'/api',challengeToken:async()=>''},dispatchEvent(){}},localStorage:{getItem:(key:string)=>saved.get(key),setItem:(key:string,value:string)=>saved.set(key,value),removeItem:(key:string)=>saved.delete(key)},location,URLSearchParams,Event,fetch:async(url:string,init:any)=>{requests.push({url,body:JSON.parse(init.body)});return Response.json(url.endsWith('/verify-email')?{verificationToken:'proof'}:{member:{id:'M-test',firstAttribution:null,currentAttribution:null},accessToken:'token',mustChangePassword});}});
 return{saved,button,form,nodes,replacements,requests};
}
test('이메일 인증 후 추천인 없이 가입하면 세션을 저장하고 홈 문서를 새로 불러온다',async()=>{const view=setup('signup');await view.nodes['#verifyEmail'].onclick();view.form.onsubmit({preventDefault(){}});await tick();assert.deepEqual(view.replacements,['/']);assert.equal(JSON.parse(view.saved.get('earthplayground-portal-v2')!).token,'token');assert.equal(view.requests.at(-1).body.directCode,'');assert.equal(view.button.disabled,true);});
test('일반 로그인은 홈을 다시 불러오고 임시 비밀번호 로그인은 변경 화면을 유지한다',async()=>{for(const temporary of [false,true]){const view=setup('login',temporary);view.form.onsubmit({preventDefault(){}});await tick();assert.equal(JSON.parse(view.saved.get('earthplayground-portal-v2')!).token,'token');assert.deepEqual(view.replacements,temporary?[]:['/']);if(temporary){assert.equal(view.form.hidden,true);assert.equal(view.nodes['#memberPasswordForm'].hidden,false);}}});
