import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../../prototype/app.js',import.meta.url),'utf8').split("document.querySelectorAll('.hotspot")[0];
function menuState(){const events:any={},navEvents:any={},pageEvents:any={};let resize:any,focused=false;const menu:any={expanded:'false',getAttribute(){return this.expanded},setAttribute(_k:string,v:string){this.expanded=v},addEventListener:(k:string,f:any)=>events[k]=f,focus(){focused=true}},nav:any={open:false,classList:{toggle(_k:string,v:boolean){nav.open=v}},addEventListener:(k:string,f:any)=>navEvents[k]=f};runInNewContext(source,{document:{querySelector:(s:string)=>s==='.menu'?menu:nav,addEventListener:(k:string,f:any)=>pageEvents[k]=f},window:{matchMedia:()=>({addEventListener(_k:string,f:any){resize=f}})}});return{menu,nav,events,navEvents,pageEvents,resize:()=>resize(),focused:()=>focused};}
test('모바일 메뉴는 링크 선택·바깥 터치·화면 회전 후 닫힌다',()=>{const v=menuState();v.events.click();assert.equal(v.nav.open,true);v.navEvents.click({target:{closest:()=>({})}});assert.equal(v.nav.open,false);assert.equal(v.menu.expanded,'false');v.events.click();v.pageEvents.click({target:{closest:()=>null}});assert.equal(v.nav.open,false);v.events.click();v.resize();assert.equal(v.nav.open,false);});
test('Escape로 닫으면 메뉴 버튼으로 키보드 포커스가 돌아온다',()=>{const v=menuState();v.events.click();v.pageEvents.keydown({key:'Escape'});assert.equal(v.nav.open,false);assert.equal(v.focused(),true);});
test('좁은 회원 폼에서는 보안 확인창을 작은 크기로 표시한다',async()=>{
 const beta=readFileSync(new URL('../../prototype/beta.js',import.meta.url),'utf8');
 for(const [width,expected] of [[240,'compact'],[360,'normal']] as const){let size='';const container={clientWidth:width,replaceChildren(){}};const site:any={apiBase:'/api'},window:any={G9STAR:site,turnstile:{render(_target:any,options:any){size=options.size;options.callback('mock-token')}}};runInNewContext(beta,{window,document:{addEventListener(){},querySelector:()=>container,createElement:()=>({}),head:{append:(s:any)=>s.onload()},body:{classList:{contains:()=>true}}},fetch:async()=>Response.json({turnstileSiteKey:'test-key'})});assert.equal(await site.challengeToken(),'mock-token');assert.equal(size,expected);}
});
