import { randomUUID } from 'node:crypto';

export type Role='CUSTOMER'|'PARTNER'|'OPERATOR'|'SUPER_ADMIN'|'MD'|'CS'|'FINANCE';
export type CouponStatus='DRAFT'|'ISSUED'|'RESERVED'|'USED'|'SUSPENDED'|'EXPIRED'|'REVOKED';
export type PartnerStatus='ACTIVE'|'REVIEW'|'ENDED';
export class DomainError extends Error{code:string;status:number;details?:unknown;constructor(code:string,message:string,status=400,details?:unknown){super(message);this.code=code;this.status=status;this.details=details}}
export interface AuditEvent{id:string;action:string;actor:string;occurredAt:string;detail:Record<string,unknown>}
export interface Referral{code:string;partnerId:string;partnerName:string;ownerId:string;status:'ACTIVE'|'SUSPENDED'|'EXPIRED'}
export interface Attribution{code:string;partnerId:string;partnerName:string;ownerId:string;confirmedAt:string}
export interface Member{id:string;name:string;firstAttribution:Attribution;currentAttribution:Attribution;scheduledAttribution?:{attribution:Attribution;effectiveFrom:string}}
export interface ChangeRequest{id:string;memberId:string;before:Attribution;after:Attribution;effectiveFrom:string;reason:string;retroactive:boolean;requestedBy:string;status:'PENDING'|'APPROVED'|'REJECTED';approvedBy?:string}
export interface Coupon{id:string;memberId:string;campaignCode:string;title:string;amount:number;minAmount:number;discountType?:'FIXED'|'PERCENT';discountValue?:number;maxDiscount?:number;discountAmount?:number;status:CouponStatus;expiresAt:string;reservationId?:string}
export interface CouponCampaign{code:string;title:string;discountType:'FIXED'|'PERCENT';discountValue:number;maxDiscount?:number;minAmount:number;status:'DRAFT'|'ACTIVE'|'SUSPENDED'|'EXPIRED'|'REVOKED';startsAt:string;endsAt:string;purchaseEnabled:boolean;rentalEnabled:boolean}
export interface Partner{id:string;name:string;status:PartnerStatus;payoutHold:boolean;lastVerifiedAt:string;endedAt?:string}
export interface LedgerItem{id:string;partnerId:string;period:string;transactionId:string;kind:'PURCHASE'|'RENTAL_UPFRONT'|'RENTAL_FINAL'|'NEGATIVE';amount:number;status:'READY'|'HOLD'|'PAID'|'CANCELLED';holdReason?:string}
export interface Settlement{id:string;partnerId:string;period:string;status:'REVIEW'|'FINAL'|'HELD'|'SPECIAL_PAY'|'PAID';disputeWindow:'OPEN'|'CLOSED';taxStatus:'MISSING'|'ERROR'|'VERIFIED';holdReason?:string;heldTransactions?:string[]}
// ST-03 마이너스 수수료 상태기계: 상계대기→일부상계/반환청구→입금확인→회수완료, 예외 연체/회수불가
export type NegativeStatus='OFFSET_PENDING'|'PARTIALLY_OFFSET'|'RECLAIM_REQUESTED'|'DEPOSIT_CONFIRMED'|'OVERDUE'|'RECOVERED'|'UNRECOVERABLE';
export interface NegativeCommission{id:string;partnerId:string;transactionId:string;originalAmount:number;remaining:number;status:NegativeStatus;reason:string;createdAt:string;history:{action:string;amount?:number;at:string;actor?:string}[]}

export const normalizeReferral=(value:string)=>value.trim().toUpperCase();
export const purchaseCommission=(sellingPrice:number,couponDiscount:number,cancelled:number,rate:number)=>Math.round(Math.max(0,sellingPrice-couponDiscount-cancelled)*rate);
export const rentalCommission=(committedRent:number,rate:number)=>{const total=Math.round(committedRent*rate);return{total,upfront:Math.round(total*.5),remaining:total-Math.round(total*.5)}};
// ST-02 렌탈 최종 정산: 인정 약정액으로 총수수료를 재계산해 선지급 50%를 제한 잔여(음수면 부족액=마이너스 수수료)
export const rentalFinalSettlement=(committedRent:number,recognizedCommitment:number,rate:number)=>{const total=Math.round(committedRent*rate),upfront=Math.round(total*.5),recognizedTotal=Math.round(recognizedCommitment*rate);return{total,upfront,recognizedTotal,finalRemaining:recognizedTotal-upfront}};
// CP-07 부분취소: 쿠폰 할인을 상품별 할인 전 금액 비례로 배분하고, 취소 상품의 실결제액(가격-배분할인)만 환불
export const proratedCouponRefund=(items:{id:string;price:number}[],couponDiscount:number,cancelledIds:string[])=>{const total=items.reduce((s,i)=>s+i.price,0)||1;let allocated=0;const shares:Record<string,number>={};items.forEach((it,index)=>{const share=index===items.length-1?couponDiscount-allocated:Math.round(couponDiscount*it.price/total);allocated+=share;shares[it.id]=share});const refund=items.filter(i=>cancelledIds.includes(i.id)).reduce((s,i)=>s+(i.price-(shares[i.id]||0)),0);return{shares,refund}};
export const id=()=>randomUUID();

export class DomainStore{
 referrals=new Map<string,Referral>();aliases=new Map<string,string>();members=new Map<string,Member>();requests=new Map<string,ChangeRequest>();campaigns=new Map<string,CouponCampaign>();coupons=new Map<string,Coupon>();partners=new Map<string,Partner>();ledger=new Map<string,LedgerItem>();settlements=new Map<string,Settlement>();negatives=new Map<string,NegativeCommission>();audit:AuditEvent[]=[];
 constructor(){
  const confirmedAt='2026-09-01T00:00:00.000Z',attribution={code:'RS-A001-KIM',partnerId:'P-A',partnerName:'A 파트너',ownerId:'KIM',confirmedAt};
  this.referrals.set('RS-A001-KIM',{code:'RS-A001-KIM',partnerId:'P-A',partnerName:'A 파트너',ownerId:'KIM',status:'ACTIVE'});this.referrals.set('RS-B002-SEO',{code:'RS-B002-SEO',partnerId:'P-B',partnerName:'B 파트너',ownerId:'SEO',status:'ACTIVE'});this.referrals.set('RS-HOLD-PARK',{code:'RS-HOLD-PARK',partnerId:'P-H',partnerName:'중지 파트너',ownerId:'PARK',status:'SUSPENDED'});
  this.partners.set('P-A',{id:'P-A',name:'A 파트너',status:'ACTIVE',payoutHold:false,lastVerifiedAt:'2025-10-15T00:00:00.000Z'});this.partners.set('P-B',{id:'P-B',name:'B 파트너',status:'ACTIVE',payoutHold:false,lastVerifiedAt:'2025-10-15T00:00:00.000Z'});
  this.campaigns.set('PARTNERA10',{code:'PARTNERA10',title:'파트너 웰컴 10,000원',discountType:'FIXED',discountValue:10000,minAmount:100000,status:'ACTIVE',startsAt:'2026-01-01T00:00:00.000Z',endsAt:'2026-12-31T14:59:59.000Z',purchaseEnabled:true,rentalEnabled:false});
  this.members.set('M-1029',{id:'M-1029',name:'홍길동',firstAttribution:{...attribution},currentAttribution:{...attribution}});
  this.ledger.set('L-1',{id:'L-1',partnerId:'P-A',period:'2026-09-01',transactionId:'O-260901',kind:'PURCHASE',amount:61600,status:'READY'});this.ledger.set('L-2',{id:'L-2',partnerId:'P-A',period:'2026-09-01',transactionId:'R-260812',kind:'RENTAL_UPFRONT',amount:480000,status:'READY'});this.ledger.set('L-3',{id:'L-3',partnerId:'P-A',period:'2026-09-01',transactionId:'O-260905',kind:'PURCHASE',amount:80000,status:'READY'});this.ledger.set('L-4',{id:'L-4',partnerId:'P-A',period:'2026-09-01',transactionId:'R-260224',kind:'NEGATIVE',amount:-130000,status:'READY'});
  this.settlements.set('S-2026-09-A',{id:'S-2026-09-A',partnerId:'P-A',period:'2026-09-01',status:'REVIEW',disputeWindow:'OPEN',taxStatus:'MISSING'});
 }
 log(action:string,actor:string,detail:Record<string,unknown>){this.audit.unshift({id:id(),action,actor,occurredAt:new Date().toISOString(),detail})}
}

export class PlatformService{
 db:DomainStore;
 constructor(db=new DomainStore()){this.db=db}
 validateReferral(raw:string){const code=normalizeReferral(raw);let ref=this.db.referrals.get(code);if(!ref){const canonical=this.db.aliases.get(code);if(canonical)ref=this.db.referrals.get(canonical)}if(!ref)throw new DomainError('REFERRAL_NOT_FOUND','존재하지 않는 추천코드입니다.',404);if(ref.status==='SUSPENDED')throw new DomainError('REFERRAL_SUSPENDED','중지된 추천코드입니다.');if(ref.status==='EXPIRED')throw new DomainError('REFERRAL_EXPIRED','만료된 추천코드입니다.');return ref}
 // RF-01 과거 코드는 alias로 보존하고 canonical로 해석한다
 registerReferralAlias(alias:string,canonicalCode:string,actor='system'){const aliasCode=normalizeReferral(alias),canonical=normalizeReferral(canonicalCode);if(aliasCode===canonical)return;if(!this.db.referrals.has(canonical))throw new DomainError('REFERRAL_NOT_FOUND','canonical 추천코드를 찾을 수 없습니다.',404);this.db.aliases.set(aliasCode,canonical);this.db.log('REFERRAL_ALIAS_REGISTERED',actor,{alias:aliasCode,canonical})}
 // RF-03 링크 유입보다 마지막 유효 직접확인 코드를 우선하되, 잘못된 직접입력은 유효한 링크를 덮어쓰지 않는다
 signup(input:{name:string;linkCode?:string;directCode?:string},actor='customer'){const resolve=(code?:string)=>{if(!code)return null;try{return this.validateReferral(code)}catch{return null}};const direct=resolve(input.directCode),link=resolve(input.linkCode),ref=direct||link;if(!ref){const raw=input.directCode||input.linkCode;if(!raw)throw new DomainError('REFERRAL_REQUIRED','추천코드가 필요합니다.');this.validateReferral(raw)!;}const chosen=ref!,source=direct?'DIRECT':'LINK',now=new Date().toISOString(),snapshot={code:chosen.code,partnerId:chosen.partnerId,partnerName:chosen.partnerName,ownerId:chosen.ownerId,confirmedAt:now},member={id:id(),name:input.name,firstAttribution:snapshot,currentAttribution:snapshot};this.db.members.set(member.id,member);this.db.log('MEMBER_SIGNUP',actor,{memberId:member.id,linkCode:input.linkCode||null,directCode:input.directCode||null,finalCode:chosen.code,source});return member}
 requestAttributionChange(input:{memberId:string;targetCode:string;effectiveFrom:string;reason:string;retroactive?:boolean},actor:string,role:Role){if(input.retroactive&&role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','소급 변경은 슈퍼관리자 권한이 필요합니다.',403);const member=this.db.members.get(input.memberId);if(!member)throw new DomainError('MEMBER_NOT_FOUND','회원을 찾을 수 없습니다.',404);const ref=this.validateReferral(input.targetCode),after={code:ref.code,partnerId:ref.partnerId,partnerName:ref.partnerName,ownerId:ref.ownerId,confirmedAt:new Date().toISOString()},req={id:id(),memberId:member.id,before:member.currentAttribution,after,effectiveFrom:input.effectiveFrom,reason:input.reason,retroactive:!!input.retroactive,requestedBy:actor,status:'PENDING' as const};this.db.requests.set(req.id,req);this.db.log('ATTRIBUTION_CHANGE_REQUESTED',actor,{requestId:req.id,before:req.before,after,effectiveFrom:req.effectiveFrom,reason:req.reason});return req}
 // RF-04 소급 승인은 즉시 반영+정산 재계산, 미래 승인은 effective_from 이후 신규 거래에만 적용(현재 귀속 유지)
 approveAttributionChange(requestId:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','슈퍼관리자 권한이 필요합니다.',403);const req=this.db.requests.get(requestId);if(!req||req.status!=='PENDING')throw new DomainError('REQUEST_NOT_PENDING','승인 대기 요청이 없습니다.',404);if(req.requestedBy===actor)throw new DomainError('SEGREGATION_OF_DUTIES','요청자와 승인자는 같을 수 없습니다.');const member=this.db.members.get(req.memberId)!,appliedImmediately=req.retroactive||new Date(req.effectiveFrom).getTime()<=Date.now();if(appliedImmediately){member.currentAttribution=req.after;member.scheduledAttribution=undefined}else{member.scheduledAttribution={attribution:req.after,effectiveFrom:req.effectiveFrom}}req.status='APPROVED';req.approvedBy=actor;this.db.log('ATTRIBUTION_CHANGE_APPROVED',actor,{requestId,before:req.before,after:req.after,effectiveFrom:req.effectiveFrom,appliedImmediately,priorTransactionsChanged:req.retroactive,recalculationRequired:req.retroactive,requestedBy:req.requestedBy,approvedBy:actor});return member}
 // RF-04 특정 시점의 유효 귀속(신규 거래 귀속 판정용): 예정 변경의 effective_from 이후면 예정 귀속을 반환
 effectiveAttribution(memberId:string,at:string=new Date().toISOString()){const m=this.db.members.get(memberId);if(!m)throw new DomainError('MEMBER_NOT_FOUND','회원을 찾을 수 없습니다.',404);if(m.scheduledAttribution&&new Date(at).getTime()>=new Date(m.scheduledAttribution.effectiveFrom).getTime())return m.scheduledAttribution.attribution;return m.currentAttribution}
 registerCoupon(memberId:string,campaignCode:string,actor='customer'){const code=campaignCode.trim().toUpperCase(),campaign=this.db.campaigns.get(code),timestamp=Date.now();if(!campaign)throw new DomainError('CAMPAIGN_NOT_FOUND','존재하지 않는 쿠폰 코드입니다.',404);if(campaign.status==='SUSPENDED'||campaign.status==='REVOKED')throw new DomainError('CAMPAIGN_SUSPENDED','중지된 캠페인입니다.',409);if(campaign.status!=='ACTIVE')throw new DomainError('CAMPAIGN_INVALID','사용할 수 없는 캠페인입니다.',409);if(timestamp<new Date(campaign.startsAt).getTime())throw new DomainError('CAMPAIGN_NOT_STARTED','아직 시작되지 않은 캠페인입니다.',409);if(timestamp>new Date(campaign.endsAt).getTime())throw new DomainError('CAMPAIGN_EXPIRED','만료된 캠페인입니다.',409);if([...this.db.coupons.values()].some(c=>c.memberId===memberId&&c.campaignCode===code))throw new DomainError('COUPON_ALREADY_ISSUED','이미 등록한 캠페인입니다.',409);const amount=campaign.discountType==='FIXED'?campaign.discountValue:0,coupon={id:id(),memberId,campaignCode:code,title:campaign.title,amount,minAmount:campaign.minAmount,discountType:campaign.discountType,discountValue:campaign.discountValue,maxDiscount:campaign.maxDiscount,status:'ISSUED' as const,expiresAt:campaign.endsAt};this.db.coupons.set(coupon.id,coupon);this.db.log('MEMBER_COUPON_ISSUED',actor,{couponId:coupon.id,memberId,campaignCode:code,attributionChanged:false});return coupon}
 reserveCoupon(couponId:string,memberId:string,eligibleSubtotal:number,reservationId:string){const c=this.db.coupons.get(couponId);if(!c||c.memberId!==memberId)throw new DomainError('COUPON_NOT_OWNED','쿠폰 소유권이 일치하지 않습니다.',403);if(c.status!=='ISSUED')throw new DomainError('COUPON_NOT_AVAILABLE','사용 가능한 쿠폰이 아닙니다.',409);if(new Date(c.expiresAt).getTime()<=Date.now())throw new DomainError('COUPON_EXPIRED','만료된 쿠폰입니다.');if(eligibleSubtotal<c.minAmount)throw new DomainError('COUPON_MINIMUM_NOT_MET','최소금액을 충족하지 못했습니다.');c.discountAmount=c.discountType==='PERCENT'?Math.min(Math.floor(eligibleSubtotal*Number(c.discountValue||0)/100),Number(c.maxDiscount||Number.MAX_SAFE_INTEGER)):c.amount;c.status='RESERVED';c.reservationId=reservationId;this.db.log('COUPON_RESERVED',memberId,{couponId,reservationId,eligibleSubtotal,discountAmount:c.discountAmount});return c}
 completeCoupon(couponId:string,reservationId:string,success:boolean,memberId?:string){const c=this.db.coupons.get(couponId);if(!c||c.status!=='RESERVED'||c.reservationId!==reservationId)throw new DomainError('RESERVATION_MISMATCH','쿠폰 예약이 일치하지 않습니다.',409);if(memberId&&c.memberId!==memberId)throw new DomainError('COUPON_NOT_OWNED','쿠폰 소유권이 일치하지 않습니다.',403);c.status=success?'USED':'ISSUED';delete c.reservationId;this.db.log(success?'COUPON_USED':'PAYMENT_FAILED_COUPON_RELEASED','system',{couponId,reservationId});return c}
 restoreFullCancellation(couponId:string,memberId?:string){const c=this.db.coupons.get(couponId);if(!c)throw new DomainError('COUPON_NOT_FOUND','쿠폰을 찾을 수 없습니다.',404);if(memberId&&c.memberId!==memberId)throw new DomainError('COUPON_NOT_OWNED','쿠폰 소유권이 일치하지 않습니다.',403);c.status='ISSUED';this.db.log('ORDER_CANCELLED_COUPON_RESTORED','system',{couponId});return c}
 holdDispute(transactionId:string,actor:string){const item=[...this.db.ledger.values()].find(x=>x.transactionId===transactionId);if(!item)throw new DomainError('LEDGER_NOT_FOUND','원장 항목을 찾을 수 없습니다.',404);item.status='HOLD';item.holdReason='DISPUTE';this.db.log('COMMISSION_DISPUTE_HELD',actor,{transactionId,otherTransactionsUnaffected:true});return item}
 releaseDispute(transactionId:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','분쟁 해제는 슈퍼관리자 권한이 필요합니다.',403);const item=[...this.db.ledger.values()].find(x=>x.transactionId===transactionId);if(!item||item.status!=='HOLD')throw new DomainError('LEDGER_NOT_HELD','HOLD 상태인 원장 항목이 없습니다.',409);item.status='READY';delete item.holdReason;this.db.log('COMMISSION_HOLD_RELEASED',actor,{transactionId,specialPayWithinBusinessDays:5});return item}
 // ST-05 분쟁이 파트너 패소(플랫폼 승/미납)로 확정: 미지급 보류액 취소, 기지급분은 환수 마이너스 수수료로 등록
 resolveDisputeAgainstPartner(transactionId:string,input:{clawbackPaid?:number},actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','분쟁 확정은 슈퍼관리자 권한이 필요합니다.',403);const item=[...this.db.ledger.values()].find(x=>x.transactionId===transactionId);if(!item||item.status!=='HOLD')throw new DomainError('LEDGER_NOT_HELD','HOLD 상태인 원장 항목이 없습니다.',409);item.status='CANCELLED';item.holdReason='DISPUTE_LOST';const clawback=Number(input.clawbackPaid||0);let negative:NegativeCommission|undefined;if(clawback>0)negative=this.registerNegativeCommission(item.partnerId,transactionId,clawback,'DISPUTE_CLAWBACK',actor);this.db.log('COMMISSION_DISPUTE_RESOLVED_AGAINST_PARTNER',actor,{transactionId,heldAmountCancelled:true,clawback,negativeId:negative?.id||null});return{item,negativeId:negative?.id||null}}
 finalizeSettlement(settlementId:string){const s=this.db.settlements.get(settlementId);if(!s)throw new DomainError('SETTLEMENT_NOT_FOUND','정산을 찾을 수 없습니다.',404);const held=[...this.db.ledger.values()].filter(x=>x.partnerId===s.partnerId&&x.status==='HOLD').map(x=>x.transactionId);s.heldTransactions=held;s.disputeWindow='CLOSED';s.status=s.taxStatus==='VERIFIED'?'FINAL':'HELD';s.holdReason=s.taxStatus==='VERIFIED'?undefined:'TAX_INVOICE';this.db.log('SETTLEMENT_AUTO_FINALIZED','system',{settlementId,noDispute:held.length===0,heldTransactions:held});return s}
 verifyTax(settlementId:string,actor:string){const s=this.db.settlements.get(settlementId);if(!s)throw new DomainError('SETTLEMENT_NOT_FOUND','정산을 찾을 수 없습니다.',404);s.taxStatus='VERIFIED';delete s.holdReason;s.status=s.disputeWindow==='CLOSED'?'SPECIAL_PAY':'REVIEW';this.db.log('TAX_INVOICE_VERIFIED',actor,{settlementId,specialPayWithinBusinessDays:s.status==='SPECIAL_PAY'?5:null});return s}
 markTaxError(settlementId:string,reason:string,actor:string){const s=this.db.settlements.get(settlementId);if(!s)throw new DomainError('SETTLEMENT_NOT_FOUND','정산을 찾을 수 없습니다.',404);s.taxStatus='ERROR';s.status='HELD';s.holdReason=reason;this.db.log('TAX_INVOICE_ERROR',actor,{settlementId,reason,scope:'partner-month-only'});return s}
 paySettlement(settlementId:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','지급 확정은 슈퍼관리자 권한이 필요합니다.',403);const s=this.db.settlements.get(settlementId);if(!s)throw new DomainError('SETTLEMENT_NOT_FOUND','정산을 찾을 수 없습니다.',404);const p=this.db.partners.get(s.partnerId);if(p?.payoutHold)throw new DomainError('PARTNER_PAYOUT_HELD','파트너 재검증 지급 HOLD를 먼저 해소하세요.',409);if(s.taxStatus!=='VERIFIED'||s.disputeWindow!=='CLOSED'||!['FINAL','SPECIAL_PAY'].includes(s.status))throw new DomainError('SETTLEMENT_NOT_PAYABLE','정산 확정과 정상 세금계산서가 모두 필요합니다.',409);s.status='PAID';this.db.log('COMMISSION_PAID',actor,{settlementId,partnerId:s.partnerId,period:s.period});return s}
 startPartnerReview(partnerId:string,reason:string,actor:string){const p=this.db.partners.get(partnerId);if(!p)throw new DomainError('PARTNER_NOT_FOUND','파트너를 찾을 수 없습니다.',404);p.status='REVIEW';p.payoutHold=true;this.db.log('PARTNER_REVERIFICATION_STARTED',actor,{partnerId,reason,payoutOnlyHold:true,attributionPreserved:true});return p}
 completePartnerReview(partnerId:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','슈퍼관리자 권한이 필요합니다.',403);const p=this.db.partners.get(partnerId);if(!p||p.status!=='REVIEW')throw new DomainError('REVIEW_NOT_ACTIVE','진행 중인 재검증이 없습니다.');p.status='ACTIVE';p.payoutHold=false;p.lastVerifiedAt=new Date().toISOString();this.db.log('PARTNER_REVERIFICATION_COMPLETED',actor,{partnerId,releaseUnpaidWithinBusinessDays:5});return p}
 endPartner(partnerId:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','슈퍼관리자 권한이 필요합니다.',403);const p=this.db.partners.get(partnerId);if(!p)throw new DomainError('PARTNER_NOT_FOUND','파트너를 찾을 수 없습니다.',404);p.status='ENDED';p.payoutHold=false;p.endedAt=new Date().toISOString();this.db.log('PARTNER_CONTRACT_ENDED',actor,{partnerId,blockNewAttribution:true,blockCodesAndCampaigns:true,settlePreEndTransactions:true});return p}
 // ST-03 마이너스 수수료 등록(부족액)
 registerNegativeCommission(partnerId:string,transactionId:string,amount:number,reason:string,actor:string){if(!Number.isFinite(amount)||amount<=0)throw new DomainError('INVALID_NEGATIVE_AMOUNT','마이너스 수수료 금액은 0보다 커야 합니다.',422);const now=new Date().toISOString(),n:NegativeCommission={id:id(),partnerId,transactionId,originalAmount:amount,remaining:amount,status:'OFFSET_PENDING',reason,createdAt:now,history:[{action:'REGISTERED',amount,at:now,actor}]};this.db.negatives.set(n.id,n);this.db.log('NEGATIVE_COMMISSION_REGISTERED',actor,{negativeId:n.id,partnerId,transactionId,amount,reason});return n}
 // ST-03 다음 정산에서 오래된 건부터 우선 공제
 offsetNegativeCommissions(partnerId:string,availableCommission:number,actor='system'){const items=[...this.db.negatives.values()].filter(n=>n.partnerId===partnerId&&n.remaining>0&&(n.status==='OFFSET_PENDING'||n.status==='PARTIALLY_OFFSET')).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));let available=Math.max(0,availableCommission),totalOffset=0;const now=new Date().toISOString();for(const n of items){if(available<=0)break;const applied=Math.min(n.remaining,available);n.remaining-=applied;available-=applied;totalOffset+=applied;n.status=n.remaining===0?'RECOVERED':'PARTIALLY_OFFSET';n.history.unshift({action:'OFFSET',amount:applied,at:now,actor})}this.db.log('NEGATIVE_COMMISSION_OFFSET',actor,{partnerId,totalOffset,remainingCommission:available});return{totalOffset,remainingCommission:available,outstanding:[...this.db.negatives.values()].filter(n=>n.partnerId===partnerId&&n.remaining>0).map(n=>({id:n.id,remaining:n.remaining,status:n.status}))}}
 // ST-03 계약종료 또는 3개월 상계불가 시 반환청구 전환
 convertNegativeToReclaim(negativeId:string,reason:string,actor:string){const n=this.db.negatives.get(negativeId);if(!n)throw new DomainError('NEGATIVE_NOT_FOUND','마이너스 수수료를 찾을 수 없습니다.',404);if(n.status!=='OFFSET_PENDING'&&n.status!=='PARTIALLY_OFFSET')throw new DomainError('NEGATIVE_NOT_RECLAIMABLE','반환청구로 전환할 수 없는 상태입니다.',409,{status:n.status});n.status='RECLAIM_REQUESTED';n.history.unshift({action:'RECLAIM_REQUESTED',at:new Date().toISOString(),actor});this.db.log('NEGATIVE_COMMISSION_RECLAIM_REQUESTED',actor,{negativeId,remaining:n.remaining,reason});return n}
 // ST-03 반환 입금 확인
 confirmNegativeDeposit(negativeId:string,amount:number,actor:string){const n=this.db.negatives.get(negativeId);if(!n)throw new DomainError('NEGATIVE_NOT_FOUND','마이너스 수수료를 찾을 수 없습니다.',404);if(n.status!=='RECLAIM_REQUESTED'&&n.status!=='DEPOSIT_CONFIRMED'&&n.status!=='OVERDUE')throw new DomainError('NEGATIVE_NOT_RECLAIM','반환청구 상태가 아닙니다.',409,{status:n.status});if(!Number.isFinite(amount)||amount<=0||amount>n.remaining)throw new DomainError('INVALID_DEPOSIT_AMOUNT','입금액이 올바르지 않습니다.',422,{remaining:n.remaining});n.remaining-=amount;n.status=n.remaining===0?'RECOVERED':'DEPOSIT_CONFIRMED';n.history.unshift({action:'DEPOSIT',amount,at:new Date().toISOString(),actor});this.db.log('NEGATIVE_COMMISSION_DEPOSIT_CONFIRMED',actor,{negativeId,amount,remaining:n.remaining,status:n.status});return n}
 markNegativeOverdue(negativeId:string,actor:string){const n=this.db.negatives.get(negativeId);if(!n)throw new DomainError('NEGATIVE_NOT_FOUND','마이너스 수수료를 찾을 수 없습니다.',404);if(n.status!=='RECLAIM_REQUESTED')throw new DomainError('NEGATIVE_NOT_RECLAIM','반환청구 상태만 연체 처리할 수 있습니다.',409,{status:n.status});n.status='OVERDUE';n.history.unshift({action:'OVERDUE',at:new Date().toISOString(),actor});this.db.log('NEGATIVE_COMMISSION_OVERDUE',actor,{negativeId,remaining:n.remaining});return n}
 markNegativeUnrecoverable(negativeId:string,reason:string,actor:string,role:Role){if(role!=='SUPER_ADMIN')throw new DomainError('FORBIDDEN','회수불가 처리는 슈퍼관리자 권한이 필요합니다.',403);const n=this.db.negatives.get(negativeId);if(!n)throw new DomainError('NEGATIVE_NOT_FOUND','마이너스 수수료를 찾을 수 없습니다.',404);n.status='UNRECOVERABLE';n.history.unshift({action:'UNRECOVERABLE',at:new Date().toISOString(),actor});this.db.log('NEGATIVE_COMMISSION_UNRECOVERABLE',actor,{negativeId,remaining:n.remaining,reason});return n}
 // ST-02 렌탈 잔여 50% 최종 정산(부족 시 마이너스 수수료 등록)
 finalizeRentalCommission(input:{contractId:string;partnerId:string;period:string;committedRent:number;recognizedCommitment:number;rate:number;terminationType?:string},actor:string){const calc=rentalFinalSettlement(input.committedRent,input.recognizedCommitment,input.rate);if(calc.finalRemaining>=0){const item:LedgerItem={id:id(),partnerId:input.partnerId,period:input.period,transactionId:input.contractId,kind:'RENTAL_FINAL',amount:calc.finalRemaining,status:'READY'};this.db.ledger.set(item.id,item);this.db.log('RENTAL_FINAL_COMMISSION_RECORDED',actor,{...item,...calc,terminationType:input.terminationType||'NORMAL'});return{kind:'RENTAL_FINAL' as const,amount:calc.finalRemaining,...calc}}const shortfall=Math.abs(calc.finalRemaining),negative=this.registerNegativeCommission(input.partnerId,input.contractId,shortfall,`RENTAL_SHORTFALL:${input.terminationType||'NORMAL'}`,actor);return{kind:'NEGATIVE' as const,amount:shortfall,negativeId:negative.id,...calc}}
 // CP-07 부분취소 비례배분(원 쿠폰 USED 유지, 확정 할인 추가 회수 없음)
 partialCancellation(couponId:string,input:{items:{id:string;price:number}[];cancelledIds:string[]},actor:string){const c=this.db.coupons.get(couponId);if(!c)throw new DomainError('COUPON_NOT_FOUND','쿠폰을 찾을 수 없습니다.',404);if(c.status!=='USED')throw new DomainError('COUPON_NOT_USED','부분취소는 사용 완료 쿠폰에만 적용됩니다.',409);const discount=Number(c.discountAmount??c.amount??0),{shares,refund}=proratedCouponRefund(input.items,discount,input.cancelledIds);this.db.log('ORDER_PARTIAL_CANCELLED',actor,{couponId,cancelledIds:input.cancelledIds,refund,shares,couponStatus:'USED',additionalDiscountRecovered:false});return{couponStatus:'USED' as const,refund,shares}}
}
