const opsModules=['partners','referrals','coupons','products','inventory','showcases','orders','claims','estimates','rentals','members','contents','notifications','settlements','admins','integrations'];
const secured={security:[{bearerAuth:[]}],responses:{'200':{description:'성공'},'401':{description:'인증 필요'},'403':{description:'권한 없음'},'422':{description:'입력 검증 실패'}}};
const adminOpsPaths=Object.fromEntries(opsModules.flatMap(module=>[
 [`/v1/admin/ops/${module}`,{get:{...secured,summary:`${module} 목록·검색·필터·페이징`},post:{...secured,summary:`${module} 생성`,responses:{...secured.responses,'201':{description:'생성'}}}}],
 [`/v1/admin/ops/${module}/export`,{get:{...secured,summary:`${module} CSV 내보내기`}}],
 [`/v1/admin/ops/${module}/bulk-status`,{post:{...secured,summary:`${module} 대량 상태변경`}}],
 [`/v1/admin/ops/${module}/{id}`,{get:{...secured,summary:`${module} 상세`,parameters:[{in:'path',name:'id',required:true,schema:{type:'string'}}]}}],
 [`/v1/admin/ops/${module}/{id}/update`,{post:{...secured,summary:`${module} 수정`}}],
 [`/v1/admin/ops/${module}/{id}/status`,{post:{...secured,summary:`${module} 상태 전이`}}]
]));

export const openapi={openapi:'3.1.0',info:{title:'지구별놀이터 Partner & Full Backoffice API',version:'0.2.0'},servers:[{url:'http://localhost:4100'}],paths:{
 '/health':{get:{summary:'서비스 및 저장소 상태',responses:{'200':{description:'정상'}}}},
 '/v1/referrals/validate':{post:{summary:'추천코드 검증',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['code'],properties:{code:{type:'string'}}}}}},responses:{'200':{description:'유효'},'404':{description:'미존재'}}}},
 '/v1/members':{post:{summary:'추천인 귀속 회원가입',responses:{'201':{description:'생성'}}}},
 '/v1/members/{memberId}/attribution-change-requests':{post:{summary:'현재 귀속 변경 요청',security:[{bearerAuth:[]}],parameters:[{in:'path',name:'memberId',required:true,schema:{type:'string'}}],responses:{'201':{description:'승인대기'}}}},
 '/v1/attribution-change-requests/{requestId}/approve':{post:{summary:'슈퍼관리자 귀속 변경 승인',security:[{bearerAuth:[]}],parameters:[{in:'path',name:'requestId',required:true,schema:{type:'string'}}],responses:{'200':{description:'승인'},'403':{description:'권한 또는 직무분리 위반'}}}},
 '/v1/showcases':{get:{summary:'공개 쇼케이스 목록(PUBLISHED)',responses:{'200':{description:'목록'}}}},
 '/v1/showcases/{id}':{get:{summary:'공개 쇼케이스 상세(핫스팟+상품 요약)',parameters:[{in:'path',name:'id',required:true,schema:{type:'string'}}],responses:{'200':{description:'상세'},'404':{description:'미공개/미존재'}}}},
 '/v1/products':{get:{summary:'공개 상품 목록(ACTIVE)',responses:{'200':{description:'목록'}}}},
 '/v1/products/{id}':{get:{summary:'공개 상품 상세(+배치 매장)',parameters:[{in:'path',name:'id',required:true,schema:{type:'string'}}],responses:{'200':{description:'상세'},'404':{description:'미판매/미존재'}}}},
 '/v1/coupons/register':{post:{summary:'회원 쿠폰 발급',responses:{'201':{description:'발급'}}}},
 '/v1/coupons/{couponId}/reserve':{post:{summary:'쿠폰 원자적 예약',responses:{'200':{description:'RESERVED'}}}},
 '/v1/coupons/{couponId}/complete':{post:{summary:'결제 결과에 따른 사용 또는 복구',responses:{'200':{description:'USED 또는 ISSUED'}}}},
 '/v1/admin/dashboard':{get:{summary:'백오피스 통합 대시보드 조회',security:[{bearerAuth:[]}],parameters:[{in:'query',name:'memberId',schema:{type:'string'}},{in:'query',name:'partnerId',schema:{type:'string'}},{in:'query',name:'period',schema:{type:'string'}}],responses:{'200':{description:'귀속·원장·정산·파트너·쿠폰·감사 통합 데이터'},'401':{description:'인증 필요'}}}},
 '/v1/admin/attribution-change-requests/{requestId}/reject':{post:{summary:'슈퍼관리자 귀속 변경 반려',security:[{bearerAuth:[]}],parameters:[{in:'path',name:'requestId',required:true,schema:{type:'string'}}],responses:{'200':{description:'반려'},'403':{description:'권한 또는 직무분리 위반'}}}},
 '/v1/admin/commission-ledger/{transactionId}/hold':{post:{summary:'거래 단위 분쟁 HOLD',security:[{bearerAuth:[]}],responses:{'200':{description:'HOLD'}}}},
 '/v1/admin/commission-ledger/{transactionId}/release':{post:{summary:'슈퍼관리자 거래 HOLD 해제(파트너 승)',security:[{bearerAuth:[]}],responses:{'200':{description:'READY'},'403':{description:'권한 없음'}}}},
 '/v1/admin/commission-ledger/{transactionId}/resolve-against-partner':{post:{summary:'ST-05 파트너 패소 분쟁 확정(보류액 취소·기지급 환수 마이너스)',security:[{bearerAuth:[]}],responses:{'200':{description:'CANCELLED + 마이너스 수수료'},'403':{description:'권한 없음'}}}},
 '/v1/admin/settlements/{settlementId}/finalize':{post:{summary:'이의기간 종료 후 월 정산 확정',security:[{bearerAuth:[]}],responses:{'200':{description:'FINAL'}}}},
 '/v1/admin/settlements/{settlementId}/tax-error':{post:{summary:'세금계산서 오류 및 파트너·월 지급 HOLD',security:[{bearerAuth:[]}],responses:{'200':{description:'HELD'}}}},
 '/v1/admin/settlements/{settlementId}/verify-tax':{post:{summary:'세금계산서 정상 확인 및 특별 지급 전환',security:[{bearerAuth:[]}],responses:{'200':{description:'VERIFIED'}}}},
 '/v1/admin/settlements/{settlementId}/pay':{post:{summary:'슈퍼관리자 지급 완료 처리',security:[{bearerAuth:[]}],responses:{'200':{description:'PAID'},'409':{description:'지급 게이트 미충족'}}}},
 '/v1/admin/partners/{partnerId}/review':{post:{summary:'파트너 재검증 시작',security:[{bearerAuth:[]}],responses:{'200':{description:'REVIEW'}}}},
 '/v1/admin/partners/{partnerId}/review-complete':{post:{summary:'슈퍼관리자 파트너 재검증 완료',security:[{bearerAuth:[]}],responses:{'200':{description:'ACTIVE'}}}},
 '/v1/admin/partners/{partnerId}/end':{post:{summary:'슈퍼관리자 파트너 계약 종료',security:[{bearerAuth:[]}],responses:{'200':{description:'ENDED'}}}},
 '/v1/admin/coupons':{post:{summary:'운영자 쿠폰 캠페인 생성',security:[{bearerAuth:[]}],responses:{'201':{description:'ACTIVE'},'409':{description:'코드 중복'}}}},
 '/v1/admin/coupons/{code}/suspend':{post:{summary:'슈퍼관리자 쿠폰 소프트 중지',security:[{bearerAuth:[]}],responses:{'200':{description:'SUSPENDED'},'409':{description:'사용 완료 쿠폰'}}}},
 '/v1/admin/coupons/{code}/restore':{post:{summary:'슈퍼관리자 중지 쿠폰 복원',security:[{bearerAuth:[]}],responses:{'200':{description:'ACTIVE'}}}},
 ...adminOpsPaths,
 '/v1/admin/ops/dashboard':{get:{...secured,summary:'운영 통합 KPI·실패·최근 업무'}},
 '/v1/admin/ops/analytics':{get:{...secured,summary:'퍼널·GMV·파트너 분석'}},
 '/v1/admin/ops/roles':{get:{...secured,summary:'Role Matrix 조회'}},
 '/v1/admin/ops/roles/{role}/permissions':{post:{...secured,summary:'Role Matrix 수정'}},
 '/v1/admin/ops/partners/{id}/api-key':{post:{...secured,summary:'파트너 API Key 1회 표시 재발급'}},
 '/v1/admin/ops/products/{id}/generate-skus':{post:{...secured,summary:'상품 옵션 조합 SKU 생성'}},
 '/v1/admin/ops/inventory/{sku}/adjust':{post:{...secured,summary:'재고 실사 조정'}},
 '/v1/admin/ops/inventory/{sku}/receive':{post:{...secured,summary:'재고 입고'}},
 '/v1/admin/ops/showcases/{id}/hotspots':{post:{...secured,summary:'쇼케이스 Hotspot 저장'}},
 '/v1/admin/ops/orders/{id}/shipment':{post:{...secured,summary:'배송사·송장 등록'}},
 '/v1/admin/ops/claims/{id}/inspect':{post:{...secured,summary:'반품 검수'}},
 '/v1/admin/ops/claims/{id}/refund':{post:{...secured,summary:'PG 환불·쿠폰·정산 조정'}},
 '/v1/admin/ops/estimates/{id}/assign':{post:{...secured,summary:'견적 담당자·다음 연락 배정'}},
 '/v1/admin/ops/estimates/{id}/revisions':{post:{...secured,summary:'견적 Revision 저장'}},
 '/v1/admin/ops/rentals/{id}/contract':{post:{...secured,summary:'렌탈 계약서 등록'}},
 '/v1/admin/ops/members/{id}/memos':{post:{...secured,summary:'회원 CRM 메모'}},
 '/v1/admin/ops/members/{id}/force-coupon':{post:{...secured,summary:'회원 쿠폰 강제 발급'}},
 '/v1/admin/ops/coupons/{id}/issue':{post:{...secured,summary:'캠페인에서 회원 쿠폰 발급'}},
 '/v1/admin/ops/coupons/{id}/suspend':{post:{...secured,summary:'캠페인 일반·긴급 중지'}},
 '/v1/admin/ops/coupons/{id}/delete':{post:{...secured,summary:'캠페인 소프트 삭제'}},
 '/v1/admin/ops/notifications/dispatch':{post:{...secured,summary:'멱등 알림 자동화 발송 예약'}},
 '/v1/admin/ops/settlements/{id}/recalculate':{post:{...secured,summary:'정산 재계산'}},
 '/v1/admin/ops/settlements/{id}/confirm':{post:{...secured,summary:'직무분리 정산 확정·잠금'}},
 '/v1/admin/ops/integrations/{id}/reprocess':{post:{...secured,summary:'실패 연동 재처리'}},
 '/v1/admin/ops/assets':{post:{...secured,summary:'상품·쇼케이스 이미지 업로드(로컬 스토리지)',description:'raw 이미지 바이트를 Content-Type(image/png,jpeg,webp,gif)과 함께 전송한다. 업로드된 파일의 상대 URL(/uploads/{filename})을 반환한다.',requestBody:{required:true,content:{'image/png':{schema:{type:'string',format:'binary'}},'image/jpeg':{schema:{type:'string',format:'binary'}},'image/webp':{schema:{type:'string',format:'binary'}},'image/gif':{schema:{type:'string',format:'binary'}}}},responses:{...secured.responses,'201':{description:'업로드 완료'},'413':{description:'용량 초과'},'415':{description:'미지원 형식'}}}},
 '/uploads/{filename}':{get:{summary:'업로드된 이미지 서빙',parameters:[{in:'path',name:'filename',required:true,schema:{type:'string'}}],responses:{'200':{description:'이미지 바이트'},'404':{description:'미존재'}}}},
 '/v1/admin/rentals/{contractId}/finalize-commission':{post:{summary:'ST-02 렌탈 잔여 50% 최종 정산(부족 시 마이너스 수수료)',security:[{bearerAuth:[]}],responses:{'201':{description:'RENTAL_FINAL 또는 NEGATIVE 등록'}}}},
 '/v1/admin/negative-commissions':{get:{summary:'ST-03 마이너스 수수료 원장 조회',security:[{bearerAuth:[]}],parameters:[{in:'query',name:'partnerId',schema:{type:'string'}}],responses:{'200':{description:'목록'}}}},
 '/v1/admin/negative-commissions/offset':{post:{summary:'ST-03 오래된 건부터 우선 상계',security:[{bearerAuth:[]}],responses:{'200':{description:'상계 결과'}}}},
 '/v1/admin/negative-commissions/{id}/reclaim':{post:{summary:'ST-03 반환청구 전환',security:[{bearerAuth:[]}],responses:{'200':{description:'RECLAIM_REQUESTED'}}}},
 '/v1/admin/negative-commissions/{id}/deposit':{post:{summary:'ST-03 반환 입금 확인',security:[{bearerAuth:[]}],responses:{'200':{description:'DEPOSIT_CONFIRMED 또는 RECOVERED'}}}},
 '/v1/admin/negative-commissions/{id}/overdue':{post:{summary:'ST-03 반환청구 연체',security:[{bearerAuth:[]}],responses:{'200':{description:'OVERDUE'}}}},
 '/v1/admin/negative-commissions/{id}/unrecoverable':{post:{summary:'ST-03 회수불가(슈퍼관리자)',security:[{bearerAuth:[]}],responses:{'200':{description:'UNRECOVERABLE'},'403':{description:'권한 없음'}}}},
 '/v1/admin/coupons/{couponId}/partial-cancellation':{post:{summary:'CP-07 부분취소 비례배분 환불(원 쿠폰 USED 유지)',security:[{bearerAuth:[]}],responses:{'200':{description:'환불액·배분내역'}}}},
 '/v1/webhooks/medusa':{post:{summary:'Medusa 서명 웹훅',parameters:[{in:'header',name:'x-medusa-signature',required:true,schema:{type:'string'}},{in:'header',name:'idempotency-key',required:true,schema:{type:'string'}}],responses:{'202':{description:'처리 완료'}}}}
},components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT'}},schemas:{ErrorResponse:{type:'object',required:['error'],properties:{error:{type:'object',required:['code','message','details','correlationId'],properties:{code:{type:'string'},message:{type:'string'},details:{type:['object','null'],additionalProperties:true},correlationId:{type:'string'}}}}}}}};
