import {createServer,IncomingMessage,ServerResponse} from 'node:http';
import {randomUUID} from 'node:crypto';
import {DomainError,PlatformService} from './domain.ts';
import {authenticate,issueToken,requireRole} from './infrastructure/auth.ts';
import {createDatabase} from './infrastructure/database.ts';
import {MedusaWebhookProcessor} from './infrastructure/webhook.ts';
import {PostgresPlatformRepository} from './infrastructure/postgres-repository.ts';
import {openapi} from './openapi.ts';
import {booleanField,integerField,isoDateTimeField,objectInput,stringField} from './input-validation.ts';
import {AdminService} from './admin-service.ts';
import {BackofficeService} from './backoffice-service.ts';
import {handleBackofficeRoute} from './backoffice-routes.ts';
import {LocalAssetStorage} from './infrastructure/storage.ts';

const service=new PlatformService(),admin=new AdminService(service),database=createDatabase(),backoffice=new BackofficeService(service,database),sql=database.mode==='postgres'?new PostgresPlatformRepository(database):null,webhooks=new MedusaWebhookProcessor(service,database),storage=new LocalAssetStorage();
await backoffice.hydrate();
await storage.ensure();
const json=(res:ServerResponse,status:number,data:unknown)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,x-correlation-id,x-medusa-signature,idempotency-key','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))};
const read=async(req:IncomingMessage)=>{const chunks:Buffer[]=[];let size=0;for await(const c of req){size+=c.length;if(size>1_048_576)throw new DomainError('PAYLOAD_TOO_LARGE','요청 본문은 1MB 이하여야 합니다.',413);chunks.push(c)}const raw=Buffer.concat(chunks);if(!raw.length)return{raw,input:{}};try{return{raw,input:objectInput(JSON.parse(raw.toString('utf8')))}}catch(error){if(error instanceof DomainError)throw error;throw new DomainError('INVALID_JSON','JSON 요청 본문 형식이 올바르지 않습니다.',400)}};
const ASSET_MAX_BYTES=Number(process.env.ASSET_MAX_BYTES||8*1024*1024);
const readRaw=async(req:IncomingMessage,limit:number)=>{const chunks:Buffer[]=[];let size=0;for await(const c of req){size+=c.length;if(size>limit)throw new DomainError('PAYLOAD_TOO_LARGE',`업로드는 ${Math.floor(limit/1024/1024)}MB 이하여야 합니다.`,413);chunks.push(c)}return Buffer.concat(chunks)};

const route=async(req:IncomingMessage,res:ServerResponse)=>{
 const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`),method=req.method||'GET';
 if(method==='OPTIONS')return json(res,204,{});
 if(method==='GET'&&url.pathname.startsWith('/uploads/')){const asset=await storage.read(decodeURIComponent(url.pathname.slice('/uploads/'.length)));res.writeHead(200,{'content-type':asset.contentType,'access-control-allow-origin':'*','cache-control':'public, max-age=86400'});return res.end(asset.data)}
 if(method==='POST'&&url.pathname==='/v1/admin/ops/assets'){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN','MD']);const raw=await readRaw(req,ASSET_MAX_BYTES);const saved=await storage.save(raw,String(req.headers['content-type']||''));service.db.log('ASSET_UPLOADED',principal.sub,{...saved});return json(res,201,saved)}
 const payload=await read(req),input=payload.input;
 if(method==='GET'&&url.pathname==='/health')return json(res,200,{status:'ok',service:'earthplayground-backend',database:database.mode,databaseHealthy:await database.health()});
 if(method==='GET'&&url.pathname==='/openapi.json')return json(res,200,openapi);
 if(method==='POST'&&url.pathname==='/dev/token'&&DEV_TOKEN_ENABLED)return json(res,200,{accessToken:await issueToken({sub:stringField(input,'sub',{required:false,max:100})||'operator01',role:(stringField(input,'role',{required:false,max:30})||'OPERATOR') as any})});
 if(method==='POST'&&url.pathname==='/v1/referrals/validate'){const code=stringField(input,'code',{max:100})!;return json(res,200,sql?await sql.validateReferral(code):service.validateReferral(code))}
 if(method==='POST'&&url.pathname==='/v1/members'){const value={name:stringField(input,'name',{max:100})!,linkCode:stringField(input,'linkCode',{required:false,max:100}),directCode:stringField(input,'directCode',{required:false,max:100})};const member=sql?await sql.signup(value,'customer'):service.signup(value,'customer');const accessToken=await issueToken({sub:String((member as any).id),role:'CUSTOMER'});return json(res,201,{...member,accessToken})}
 if(method==='POST'&&url.pathname.match(/^\/v1\/members\/[^/]+\/attribution-change-requests$/)){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);const memberId=url.pathname.split('/')[3],value={memberId,targetCode:stringField(input,'targetCode',{max:100})!,effectiveFrom:isoDateTimeField(input,'effectiveFrom'),reason:stringField(input,'reason',{max:500})!,retroactive:booleanField(input,'retroactive',{required:false})};return json(res,201,sql?await sql.requestAttributionChange(value,principal.sub,principal.role):service.requestAttributionChange(value,principal.sub,principal.role))}
 const approve=url.pathname.match(/^\/v1\/attribution-change-requests\/([^/]+)\/approve$/);if(method==='POST'&&approve){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,sql?await sql.approveAttributionChange(approve[1],principal.sub):service.approveAttributionChange(approve[1],principal.sub,principal.role))}
 if(method==='GET'&&url.pathname==='/v1/showcases')return json(res,200,backoffice.storefrontShowcases());
 const showcaseGet=url.pathname.match(/^\/v1\/showcases\/([^/]+)$/);if(method==='GET'&&showcaseGet)return json(res,200,backoffice.storefrontShowcase(decodeURIComponent(showcaseGet[1])));
 if(method==='GET'&&url.pathname==='/v1/products')return json(res,200,backoffice.storefrontProducts());
 const productGet=url.pathname.match(/^\/v1\/products\/([^/]+)$/);if(method==='GET'&&productGet)return json(res,200,backoffice.storefrontProduct(decodeURIComponent(productGet[1])));
 if(method==='GET'&&url.pathname==='/v1/rental-items')return json(res,200,backoffice.storefrontRentalItems());
 const rentalItemGet=url.pathname.match(/^\/v1\/rental-items\/([^/]+)$/);if(method==='GET'&&rentalItemGet)return json(res,200,backoffice.storefrontRentalItem(decodeURIComponent(rentalItemGet[1])));
 if(method==='POST'&&url.pathname==='/v1/coupons/register'){const principal=await authenticate(req);const memberId=principal.sub,campaignCode=stringField(input,'campaignCode',{max:100})!;return json(res,201,sql?await sql.registerCoupon(memberId,campaignCode,'customer'):service.registerCoupon(memberId,campaignCode,'customer'))}
 const reserve=url.pathname.match(/^\/v1\/coupons\/([^/]+)\/reserve$/);if(method==='POST'&&reserve){const principal=await authenticate(req);const memberId=principal.sub,eligibleSubtotal=integerField(input,'eligibleSubtotal'),reservationId=stringField(input,'reservationId',{max:200})!;return json(res,200,sql?await sql.reserveCoupon(reserve[1],memberId,eligibleSubtotal,reservationId):service.reserveCoupon(reserve[1],memberId,eligibleSubtotal,reservationId))}
 const complete=url.pathname.match(/^\/v1\/coupons\/([^/]+)\/complete$/);if(method==='POST'&&complete){const principal=await authenticate(req);const reservationId=stringField(input,'reservationId',{max:200})!,success=booleanField(input,'success')!;return json(res,200,sql?await sql.completeCoupon(complete[1],reservationId,success):service.completeCoupon(complete[1],reservationId,success,principal.sub))}
 const cancel=url.pathname.match(/^\/v1\/coupons\/([^/]+)\/restore-full-cancellation$/);if(method==='POST'&&cancel){const principal=await authenticate(req);const orderId=stringField(input,'orderId',{max:200})!;return json(res,200,sql?await sql.restoreFullCancellation(cancel[1],orderId):service.restoreFullCancellation(cancel[1],principal.sub))}
 const backofficeResult=await handleBackofficeRoute(req,url,method,input,backoffice);if(backofficeResult){await backoffice.flush();return json(res,backofficeResult.status,backofficeResult.data)}
 if(method==='GET'&&url.pathname==='/v1/admin/dashboard'){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,admin.dashboard(url.searchParams.get('memberId')||undefined,url.searchParams.get('partnerId')||undefined,url.searchParams.get('period')||undefined))}
 const reject=url.pathname.match(/^\/v1\/admin\/attribution-change-requests\/([^/]+)\/reject$/);if(method==='POST'&&reject){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,admin.rejectAttribution(reject[1],stringField(input,'reason',{max:500})!,principal.sub,principal.role))}
 const hold=url.pathname.match(/^\/v1\/admin\/commission-ledger\/([^/]+)\/hold$/);if(method==='POST'&&hold){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,service.holdDispute(hold[1],principal.sub))}
 const release=url.pathname.match(/^\/v1\/admin\/commission-ledger\/([^/]+)\/release$/);if(method==='POST'&&release){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.releaseDispute(release[1],principal.sub,principal.role))}
 const resolveAgainst=url.pathname.match(/^\/v1\/admin\/commission-ledger\/([^/]+)\/resolve-against-partner$/);if(method==='POST'&&resolveAgainst){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.resolveDisputeAgainstPartner(resolveAgainst[1],{clawbackPaid:input.clawbackPaid===undefined?0:integerField(input,'clawbackPaid',{min:0})},principal.sub,principal.role))}
 const finalize=url.pathname.match(/^\/v1\/admin\/settlements\/([^/]+)\/finalize$/);if(method==='POST'&&finalize){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,service.finalizeSettlement(finalize[1]))}
 const taxError=url.pathname.match(/^\/v1\/admin\/settlements\/([^/]+)\/tax-error$/);if(method==='POST'&&taxError){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,service.markTaxError(taxError[1],stringField(input,'reason',{max:500})!,principal.sub))}
 const taxVerify=url.pathname.match(/^\/v1\/admin\/settlements\/([^/]+)\/verify-tax$/);if(method==='POST'&&taxVerify){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,service.verifyTax(taxVerify[1],principal.sub))}
 const pay=url.pathname.match(/^\/v1\/admin\/settlements\/([^/]+)\/pay$/);if(method==='POST'&&pay){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.paySettlement(pay[1],principal.sub,principal.role))}
 const review=url.pathname.match(/^\/v1\/admin\/partners\/([^/]+)\/review$/);if(method==='POST'&&review){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,service.startPartnerReview(review[1],stringField(input,'reason',{max:100})!,principal.sub))}
 const reviewComplete=url.pathname.match(/^\/v1\/admin\/partners\/([^/]+)\/review-complete$/);if(method==='POST'&&reviewComplete){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.completePartnerReview(reviewComplete[1],principal.sub,principal.role))}
 const partnerEnd=url.pathname.match(/^\/v1\/admin\/partners\/([^/]+)\/end$/);if(method==='POST'&&partnerEnd){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.endPartner(partnerEnd[1],principal.sub,principal.role))}
 if(method==='POST'&&url.pathname==='/v1/admin/coupons'){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,201,admin.createCoupon({code:stringField(input,'code',{max:50})!,target:stringField(input,'target',{max:100})!,partnerId:stringField(input,'partnerId',{required:false,max:100}),benefit:stringField(input,'benefit',{max:100})!},principal.sub))}
 const couponSuspend=url.pathname.match(/^\/v1\/admin\/coupons\/([^/]+)\/suspend$/);if(method==='POST'&&couponSuspend){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,admin.suspendCoupon(decodeURIComponent(couponSuspend[1]),stringField(input,'reason',{max:500})!,principal.sub,principal.role))}
 const couponRestore=url.pathname.match(/^\/v1\/admin\/coupons\/([^/]+)\/restore$/);if(method==='POST'&&couponRestore){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,admin.restoreCoupon(decodeURIComponent(couponRestore[1]),principal.sub,principal.role))}
 if(method==='POST'&&url.pathname==='/v1/webhooks/medusa'){webhooks.verify(payload.raw,String(req.headers['x-medusa-signature']||''));const result=await webhooks.process(String(req.headers['idempotency-key']||''),input);return json(res,202,result)}
 const rentalFinal=url.pathname.match(/^\/v1\/admin\/rentals\/([^/]+)\/finalize-commission$/);if(method==='POST'&&rentalFinal){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);const rate=Number(input.rate);if(!(rate>0&&rate<1))throw new DomainError('VALIDATION_ERROR','rate는 0과 1 사이여야 합니다.',422,{field:'rate'});return json(res,201,service.finalizeRentalCommission({contractId:decodeURIComponent(rentalFinal[1]),partnerId:stringField(input,'partnerId',{max:100})!,period:stringField(input,'period',{max:20})!,committedRent:integerField(input,'committedRent'),recognizedCommitment:integerField(input,'recognizedCommitment'),rate,terminationType:stringField(input,'terminationType',{required:false,max:30})},principal.sub))}
 if(method==='GET'&&url.pathname==='/v1/admin/negative-commissions'){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);const partnerId=url.searchParams.get('partnerId')||undefined;return json(res,200,{items:[...service.db.negatives.values()].filter(n=>!partnerId||n.partnerId===partnerId)})}
 if(method==='POST'&&url.pathname==='/v1/admin/negative-commissions/offset'){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);return json(res,200,service.offsetNegativeCommissions(stringField(input,'partnerId',{max:100})!,integerField(input,'availableCommission'),principal.sub))}
 const negReclaim=url.pathname.match(/^\/v1\/admin\/negative-commissions\/([^/]+)\/reclaim$/);if(method==='POST'&&negReclaim){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);return json(res,200,service.convertNegativeToReclaim(decodeURIComponent(negReclaim[1]),stringField(input,'reason',{max:500})!,principal.sub))}
 const negDeposit=url.pathname.match(/^\/v1\/admin\/negative-commissions\/([^/]+)\/deposit$/);if(method==='POST'&&negDeposit){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);return json(res,200,service.confirmNegativeDeposit(decodeURIComponent(negDeposit[1]),integerField(input,'amount',{min:1}),principal.sub))}
 const negOverdue=url.pathname.match(/^\/v1\/admin\/negative-commissions\/([^/]+)\/overdue$/);if(method==='POST'&&negOverdue){const principal=await authenticate(req);requireRole(principal,['FINANCE','OPERATOR','SUPER_ADMIN']);return json(res,200,service.markNegativeOverdue(decodeURIComponent(negOverdue[1]),principal.sub))}
 const negUnrec=url.pathname.match(/^\/v1\/admin\/negative-commissions\/([^/]+)\/unrecoverable$/);if(method==='POST'&&negUnrec){const principal=await authenticate(req);requireRole(principal,['SUPER_ADMIN']);return json(res,200,service.markNegativeUnrecoverable(decodeURIComponent(negUnrec[1]),stringField(input,'reason',{max:500})!,principal.sub,principal.role))}
 const partialCancel=url.pathname.match(/^\/v1\/admin\/coupons\/([^/]+)\/partial-cancellation$/);if(method==='POST'&&partialCancel){const principal=await authenticate(req);requireRole(principal,['CS','FINANCE','OPERATOR','SUPER_ADMIN']);const items=Array.isArray(input.items)?input.items.map((it:any)=>({id:stringField(it,'id',{max:100})!,price:integerField(it,'price')})):null;if(!items||!items.length)throw new DomainError('VALIDATION_ERROR','items는 1개 이상의 배열이어야 합니다.',422,{field:'items'});const cancelledIds=Array.isArray(input.cancelledIds)?input.cancelledIds.map(String):[];return json(res,200,service.partialCancellation(decodeURIComponent(partialCancel[1]),{items,cancelledIds},principal.sub))}
 if(method==='GET'&&url.pathname==='/v1/audit-events'){const principal=await authenticate(req);requireRole(principal,['OPERATOR','SUPER_ADMIN']);return json(res,200,{items:service.db.audit})}
 return json(res,404,{error:{code:'ROUTE_NOT_FOUND',message:'경로를 찾을 수 없습니다.'}});
};
// 개발용 무인증 토큰 발급은 ALLOW_DEV_TOKEN=true 일 때만 활성화한다(기본 비활성).
const DEV_TOKEN_ENABLED=process.env.ALLOW_DEV_TOKEN==='true';
// 운영 배포(개발 토큰 비활성) 시 약한 기본 시크릿으로 조용히 기동하지 않도록 fail-fast 검증한다.
const DEFAULT_JWT_SECRET='development-only-change-me-32-characters',DEFAULT_WEBHOOK_SECRET='development-webhook-secret';
if(!DEV_TOKEN_ENABLED){
 const problems:string[]=[];
 if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32||process.env.JWT_SECRET===DEFAULT_JWT_SECRET)problems.push('JWT_SECRET(32자 이상, 기본값 불가)');
 if(!process.env.MEDUSA_WEBHOOK_SECRET||process.env.MEDUSA_WEBHOOK_SECRET===DEFAULT_WEBHOOK_SECRET)problems.push('MEDUSA_WEBHOOK_SECRET(기본값 불가)');
 if(problems.length){console.error(`[보안] 필수 시크릿 누락으로 기동을 중단합니다: ${problems.join(', ')}. 로컬 개발은 ALLOW_DEV_TOKEN=true 로 실행하세요.`);process.exit(1)}
}
const server=createServer((req,res)=>route(req,res).catch(error=>{const e=error instanceof DomainError?error:new DomainError('INTERNAL_ERROR','서버 오류가 발생했습니다.',500),correlationId=String(req.headers['x-correlation-id']||randomUUID());res.setHeader('x-correlation-id',correlationId);json(res,e.status,{error:{code:e.code,message:e.message,details:e.details??null,correlationId}})}));
const port=Number(process.env.PORT||4100);server.listen(port,()=>console.log(`earthplayground backend listening on :${port} (${database.mode})`));
const shutdown=async()=>{server.close();await database.close()};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
