import {DomainError} from '../backend/src/domain.ts';
const fail=(message:string,status=422):never=>{throw new DomainError('VALIDATION_ERROR',message,status)};
const text=(value:any,label:string,max=100)=>{if(typeof value!=='string'||!value.trim()||value.length>max)fail(label+'을 확인하세요.');return value.trim()};
export function memberPortal(app:any,a:any,path:string,method:string,input:()=>any):Response|null{
 const base='/api/v1/member-auth/';
 a.favorites ||= [];a.cart ||= [];a.notifications ||= [];
 const member=app.service.db.members.get(a.memberId);
 const spaces:Record<string,string>={cafe:'성수동 내추럴 카페',bakery:'연남 모닝 베이커리',ramen:'을지로 카운터 라멘',salon:'한남 소프트 살롱',retail:'망원 라이프스타일 숍',office:'성수 크리에이티브 오피스'};
 const describe=(entry:any)=>{if(entry.type==='space')return {...entry,name:spaces[entry.id],price:null,image:'',href:'/showcase?space='+encodeURIComponent(entry.id),available:true};try{const item=entry.type==='showcase'?app.backoffice.storefrontShowcase(entry.id):app.backoffice.storefrontProduct(entry.id);return {...entry,name:item.name||item.title,price:item.salePrice??null,image:item.images?.[0]||item.imageUrl||'',href:entry.type==='showcase'?'/showcase?id='+encodeURIComponent(entry.id):'/product?id='+encodeURIComponent(entry.id),available:true};}catch{return {...entry,name:'현재 제공되지 않는 항목',price:null,image:'',href:null,available:false};}};
 const result=()=>({profile:{email:a.email,name:member.name,phone:a.phone},favorites:a.favorites.map(describe),cart:a.cart.map((entry:any)=>describe({...entry,type:'product'})),coupons:[...app.service.db.coupons.values()].filter((c:any)=>c.memberId===a.memberId),notifications:a.notifications});
 const note=(message:string)=>{a.notifications.unshift({id:crypto.randomUUID(),message,createdAt:new Date().toISOString(),read:false});a.notifications=a.notifications.slice(0,100)};
 if(path===base+'profile'&&method==='GET')return Response.json(result());
 if(path===base+'profile'&&method==='POST'){const i=input(),name=text(i.name,'이름'),phone=String(i.phone||'').replace(/[-\s]/g,'');if(!/^01[016789]\d{7,8}$/.test(phone))fail('휴대전화 번호를 확인하세요.');member.name=name;a.phone=phone;app.backoffice.update('members',a.memberId,{name,phone},a.memberId,'CUSTOMER');note('내 정보가 변경되었습니다.');return Response.json(result());}
 if(path===base+'favorites'&&method==='POST'){const i=input(),id=text(i.id,'항목'),type=i.type;if(!['product','showcase','space'].includes(type))fail('찜 항목을 확인하세요.');const index=a.favorites.findIndex((r:any)=>r.id===id&&r.type===type);if(i.remove===true){if(index>=0)a.favorites.splice(index,1);}else if(index<0){if(a.favorites.length>=100)fail('찜은 최대 100개까지 저장할 수 있습니다.');if(type==='product')app.backoffice.storefrontProduct(id);else if(type==='showcase')app.backoffice.storefrontShowcase(id);else if(!spaces[id])fail('관심 공간을 확인하세요.');a.favorites.unshift({id,type,savedAt:new Date().toISOString()});}return Response.json(result());}
 if(path===base+'cart'&&method==='POST'){const i=input(),id=text(i.id,'상품'),index=a.cart.findIndex((r:any)=>r.id===id);if(i.remove===true){if(index>=0)a.cart.splice(index,1);}else{const quantity=i.add===true&&index>=0?a.cart[index].quantity+i.quantity:i.quantity;if(!Number.isSafeInteger(quantity)||quantity<1||quantity>99)fail('수량은 1~99개로 입력하세요.');app.backoffice.storefrontProduct(id);const color=typeof i.color==='string'?i.color.slice(0,100):'',size=typeof i.size==='string'?i.size.slice(0,100):'';if(index>=0)Object.assign(a.cart[index],{quantity,...(i.color!==undefined?{color}:{}),...(i.size!==undefined?{size}:{})});else{if(a.cart.length>=100)fail('장바구니는 최대 100개 상품까지 저장할 수 있습니다.');a.cart.push({id,quantity,color,size});}}return Response.json(result());}
 if(path===base+'notifications/read'&&method==='POST'){const i=input();for(const n of a.notifications)if(i.all===true||n.id===i.id)n.read=true;return Response.json(result());}
 return null;
}
