import {createHmac,timingSafeEqual} from 'node:crypto';import {DomainError,PlatformService,purchaseCommission,rentalCommission,id} from '../domain.ts';import type {Database} from './database.ts';
type Query=(sql:string,params?:unknown[])=>Promise<{rows:any[]}>;
export class MedusaWebhookProcessor{
 private seen=new Set<string>();private service:PlatformService;private database:Database;constructor(service:PlatformService,database:Database){this.service=service;this.database=database}
 verify(raw:Buffer,signature:string|undefined){if(!signature)throw new DomainError('WEBHOOK_SIGNATURE_REQUIRED','웹훅 서명이 필요합니다.',401);const expected=createHmac('sha256',process.env.MEDUSA_WEBHOOK_SECRET||'development-webhook-secret').update(raw).digest('hex'),a=Buffer.from(expected),b=Buffer.from(signature);if(a.length!==b.length||!timingSafeEqual(a,b))throw new DomainError('WEBHOOK_SIGNATURE_INVALID','웹훅 서명이 올바르지 않습니다.',401)}
 // 인메모리(개발/테스트) 경로: 도메인 Map에 원장 기록
 private applyMemory(event:any){
  if(event.type==='order.payment_captured'){const amount=purchaseCommission(event.data.sellingPrice,event.data.couponDiscount||0,event.data.cancelledAmount||0,event.data.commissionRate);const item={id:id(),partnerId:event.data.partnerId,period:event.data.period,transactionId:event.data.orderId,kind:'PURCHASE' as const,amount,status:'READY' as const};this.service.db.ledger.set(item.id,item);this.service.db.log('PURCHASE_COMMISSION_RECORDED','medusa',{...item})}
  if(event.type==='rental.activated'){if(!event.data.contractSigned||!event.data.installedAccepted||!event.data.firstPaymentCollected)throw new DomainError('RENTAL_UPFRONT_GATES_NOT_MET','렌탈 선 정산 조건이 충족되지 않았습니다.');const calc=rentalCommission(event.data.committedRent,event.data.commissionRate),item={id:id(),partnerId:event.data.partnerId,period:event.data.period,transactionId:event.data.contractId,kind:'RENTAL_UPFRONT' as const,amount:calc.upfront,status:'READY' as const};this.service.db.ledger.set(item.id,item);this.service.db.log('RENTAL_UPFRONT_COMMISSION_RECORDED','medusa',{...item,totalCommission:calc.total})}
 }
 // PostgreSQL(운영) 경로: 커미션 원장을 최종 저장소에 기록(같은 트랜잭션·멱등)
 private async applyPostgres(query:Query,event:any){
  if(event.type==='order.payment_captured'){const d=event.data,amount=purchaseCommission(d.sellingPrice,d.couponDiscount||0,d.cancelledAmount||0,d.commissionRate),calc={sellingPrice:d.sellingPrice,couponDiscount:d.couponDiscount||0,cancelledAmount:d.cancelledAmount||0,commissionRate:d.commissionRate};const inserted=await query(`insert into commission_ledger(partner_id,period,transaction_id,kind,amount_krw,status,calculation) select id,$2,$3,'PURCHASE',$4,'READY',$5::jsonb from partners where code=$1 on conflict(transaction_id,kind) do nothing returning id`,[d.partnerId,d.period,d.orderId,amount,JSON.stringify(calc)]);if(!inserted.rows.length){const exists=await query(`select 1 from partners where code=$1`,[d.partnerId]);if(!exists.rows.length)throw new DomainError('PARTNER_NOT_FOUND','수수료 대상 파트너를 찾을 수 없습니다.',404,{partnerId:d.partnerId});return}await query(`insert into audit_events(entity_type,entity_id,action,after_data,actor_id) values('COMMISSION_LEDGER',$1,'PURCHASE_COMMISSION_RECORDED',$2::jsonb,'medusa')`,[inserted.rows[0].id,JSON.stringify({transactionId:d.orderId,amount})])}
  if(event.type==='rental.activated'){const d=event.data;if(!d.contractSigned||!d.installedAccepted||!d.firstPaymentCollected)throw new DomainError('RENTAL_UPFRONT_GATES_NOT_MET','렌탈 선 정산 조건이 충족되지 않았습니다.');const calc=rentalCommission(d.committedRent,d.commissionRate),inserted=await query(`insert into commission_ledger(partner_id,period,transaction_id,kind,amount_krw,status,calculation) select id,$2,$3,'RENTAL_UPFRONT',$4,'READY',$5::jsonb from partners where code=$1 on conflict(transaction_id,kind) do nothing returning id`,[d.partnerId,d.period,d.contractId,calc.upfront,JSON.stringify({committedRent:d.committedRent,commissionRate:d.commissionRate,total:calc.total,upfront:calc.upfront})]);if(!inserted.rows.length){const exists=await query(`select 1 from partners where code=$1`,[d.partnerId]);if(!exists.rows.length)throw new DomainError('PARTNER_NOT_FOUND','수수료 대상 파트너를 찾을 수 없습니다.',404,{partnerId:d.partnerId});return}await query(`insert into audit_events(entity_type,entity_id,action,after_data,actor_id) values('COMMISSION_LEDGER',$1,'RENTAL_UPFRONT_COMMISSION_RECORDED',$2::jsonb,'medusa')`,[inserted.rows[0].id,JSON.stringify({transactionId:d.contractId,amount:calc.upfront,totalCommission:calc.total})])}
 }
 async process(key:string|undefined,event:any){if(!key)throw new DomainError('IDEMPOTENCY_KEY_REQUIRED','멱등키가 필요합니다.');if(this.seen.has(key))return{duplicate:true};const result=await this.database.withTransaction(async(query:Query)=>{if(this.database.mode==='postgres'){const inserted=await query('insert into webhook_events(idempotency_key,event_type,payload) values($1,$2,$3::jsonb) on conflict do nothing returning id',[key,event.type,JSON.stringify(event)]);if(!inserted.rows.length)return{duplicate:true};await this.applyPostgres(query,event);return{duplicate:false,accepted:true}}this.applyMemory(event);return{duplicate:false,accepted:true}});if(!(result as any).duplicate)this.seen.add(key);return result}
}
