(function(){
 let session=null;try{session=JSON.parse(sessionStorage.getItem('g9star-admin-session')||'null');if(session){const payload=JSON.parse(atob(session.accessToken.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(payload.exp*1000<Date.now())session=null}}catch{session=null}
 window.G9STAR.adminSession=session;
 const panel=document.querySelector('#adminLoginPanel'),layout=document.querySelector('.admin-layout'),message=document.querySelector('#adminLoginMessage');panel.hidden=!!session;layout.hidden=!session||!!session.mustChangePassword;
 document.querySelector('.role-switch').hidden=true;document.querySelector('[data-module="admins"]').hidden=session?.role!=='SUPER_ADMIN';document.querySelector('#activeUser').textContent=session?.user||'로그인 필요';
 const permissions=session?.permissions||(['SUPER_ADMIN','OPERATOR'].includes(session?.role)?['*']:[]);window.G9STAR.adminCanRead=module=>module==='admins'?session?.role==='SUPER_ADMIN':permissions.includes('*')||permissions.includes(module+':read')||permissions.includes(module+':write');

 const originalFetch=window.fetch.bind(window);
 function endSession(text){if(!window.G9STAR.adminSession)return;sessionStorage.removeItem('g9star-admin-session');window.G9STAR.adminSession=null;session=null;layout.hidden=true;panel.hidden=false;document.querySelectorAll('.admin-account-control').forEach(b=>b.remove());document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.querySelector('#activeUser').textContent='로그인 필요';message.textContent=text||'로그인이 종료되었습니다. 다시 로그인하세요.';document.querySelector('#adminPassword').value='';}
 window.fetch=async(...args)=>{const response=await originalFetch(...args),url=String(args[0] instanceof Request?args[0].url:args[0]);if(response.status===401&&url.includes('/v1/admin/')&&!url.includes('/v1/admin/login')){const body=await response.clone().json().catch(()=>({}));endSession(body.error?.message);}return response;};
 async function post(path,body){const response=await fetch(window.G9STAR.apiBase+'/v1/admin/'+path,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+session?.accessToken},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'처리하지 못했습니다.');return data;}
 const eye='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>',eyeOff='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 3 18 18M10 5.2c.6-.1 1.3-.2 2-.2 6.5 0 10 7 10 7a20 20 0 0 1-3.2 4M6 6.2A20 20 0 0 0 2 12s3.5 7 10 7a12 12 0 0 0 5-.9M10 10a3 3 0 0 0 4 4"/></svg>';
 function passwordVisibility(input,label){const wrapper=document.createElement('span');wrapper.className='password-input-wrap';input.parentNode.insertBefore(wrapper,input);wrapper.append(input);const toggle=document.createElement('button');toggle.type='button';toggle.className='password-visibility';input.setAttribute('aria-label',label);toggle.setAttribute('aria-controls',input.id);toggle.setAttribute('aria-pressed','false');const update=()=>{const shown=input.type==='text';toggle.innerHTML=shown?eyeOff:eye;toggle.title=shown?'비밀번호 숨기기':'비밀번호 보기';toggle.setAttribute('aria-label',label+(shown?' 숨기기':' 보기'));toggle.setAttribute('aria-pressed',String(shown));};toggle.onclick=()=>{input.type=input.type==='password'?'text':'password';update();};update();wrapper.append(toggle);}
 passwordVisibility(document.querySelector('#adminPassword'),'로그인 비밀번호');
 // Account credentials are entered in password fields, never in the JSON editor.
 window.G9STAR.adminAccountForm=(action,item={})=>new Promise(resolve=>{
  const dialog=document.createElement('dialog');dialog.className='admin-dialog credential-dialog';const form=document.createElement('form');form.className='admin-form credential-form';const title=document.createElement('h2');title.textContent=({create:'관리자 추가',edit:'이름·권한 수정',status:'사용 상태 변경','reset-password':'비밀번호 재설정',password:'비밀번호 변경'})[action];const heading=document.createElement('div');heading.className='credential-heading';dialog.setAttribute('aria-label',title.textContent);heading.append(title);const close=document.createElement('button');close.type='button';close.className='credential-close';close.textContent='×';close.setAttribute('aria-label','닫기');close.onclick=()=>dialog.close();heading.append(close);form.append(heading);
  const controls={};function field(key,label,type,value,options){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement(options?'select':'input');input.name=key;if(options)options.forEach(([v,t])=>input.add(new Option(t,v)));else input.type=type;input.value=value||'';input.required=true;if(type==='password'){input.minLength=key==='currentPassword'?1:8;input.maxLength=200;input.autocomplete=key==='currentPassword'?'current-password':'new-password';}wrap.append(input);form.append(wrap);if(type==='password'){input.id='admin-credential-'+key;passwordVisibility(input,label);}controls[key]=input;}
  if(['create','edit'].includes(action)){field('name','이름','text',item.name);if(action==='create')field('email','로그인 이메일','email','');field('role','권한','',item.role||'CS',[['OPERATOR','운영'],['MD','상품·견적'],['CS','고객 지원'],['FINANCE','정산']]);}
  if(action==='status')field('status','사용 상태','',item.status,[['ACTIVE','사용 가능'],['SUSPENDED','사용 중지']]);
  if(action==='password')field('currentPassword',session?.mustChangePassword?'임시 비밀번호 입력':'기존 비밀번호 입력','password','');
  if(['create','reset-password','password'].includes(action)){field(action==='password'?'newPassword':'password','신규 비밀번호 입력','password','');field('confirm','신규 비밀번호 확인','password','');}
  if(['create','reset-password','password'].includes(action)){const hint=document.createElement('small');hint.className='credential-hint';hint.textContent='영문·숫자·특수문자를 포함한 8자 이상';form.append(hint);}
  const error=document.createElement('p');error.className='admin-message error';error.setAttribute('role','status');form.append(error);const save=document.createElement('button');save.type='submit';save.className='admin-button primary';save.textContent='확정';form.append(save);dialog.append(form);document.body.append(dialog);let result=null;
  form.onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(Object.entries(controls).map(([key,input])=>[key,input.value]));if(controls.confirm&&data.confirm!==(data.password||data.newPassword)){error.textContent='새 비밀번호 확인이 일치하지 않습니다.';return;}const next=data.password||data.newPassword;if(next&&(next.length<8||next.length>200||!/[A-Za-z]/.test(next)||!/[0-9]/.test(next)||!/[\x21-\x2f\x3a-\x40\x5b-\x60\x7b-\x7e]/.test(next))){error.textContent='비밀번호는 영문·숫자·특수문자를 모두 포함한 8~200자로 입력하세요.';return;}delete data.confirm;
   if(action==='password'){save.disabled=true;try{await post('password',data);endSession('비밀번호를 변경했습니다. 새 비밀번호로 로그인하세요.');dialog.close();}catch(e){error.textContent=e.message;save.disabled=false;}}else{result=data;dialog.close();}
  };dialog.onclose=()=>{dialog.remove();resolve(result);};dialog.showModal();
 });
 if(session){if(session.mustChangePassword)queueMicrotask(()=>window.G9STAR.adminAccountForm('password'));document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===session.role));for(const [label,action] of [['비밀번호 변경',()=>window.G9STAR.adminAccountForm('password')],['로그아웃',async()=>{try{await post('logout',{});endSession('로그아웃했습니다.');}catch(e){message.textContent=e.message;}}]]){const button=document.createElement('button');button.textContent=label;button.className='admin-button admin-account-control';button.onclick=action;document.querySelector('.admin-header').append(button);}
  const check=async()=>{if(!session)return;try{await fetch(window.G9STAR.apiBase+'/v1/admin/session',{headers:{authorization:'Bearer '+session.accessToken},cache:'no-store'});}catch{}};check();setInterval(check,15000);window.addEventListener('focus',check);
 }
 const recoveryButton=document.createElement('button');recoveryButton.type='button';recoveryButton.className='admin-recovery-link';recoveryButton.textContent='비밀번호를 잊으셨나요?';document.querySelector('#adminLoginForm').append(recoveryButton);
 recoveryButton.onclick=()=>{const dialog=document.createElement('dialog');dialog.className='admin-dialog credential-dialog';const form=document.createElement('form');form.className='credential-form';const heading=document.createElement('div');heading.className='credential-heading';const title=document.createElement('h2');title.textContent='임시 비밀번호 받기';dialog.setAttribute('aria-label',title.textContent);const close=document.createElement('button');close.type='button';close.className='credential-close';close.textContent='×';close.setAttribute('aria-label','닫기');close.onclick=()=>dialog.close();heading.append(title,close);form.append(heading);const label=document.createElement('label');label.textContent='등록된 관리자 이메일';const email=document.createElement('input');email.type='email';email.required=true;email.autocomplete='username';email.value=document.querySelector('#adminLogin').value;label.append(email);form.append(label);const hint=document.createElement('small');hint.className='credential-hint';hint.textContent='임시 비밀번호는 15분간 유효하며, 로그인 후 변경해야 합니다. 재발송은 1분 간격, 시간당 최대 3회입니다.';const challenge=document.createElement('div');challenge.id='adminRecoveryChallenge';const status=document.createElement('p');status.setAttribute('role','status');const send=document.createElement('button');send.type='submit';send.className='admin-button primary';send.textContent='임시 비밀번호 발송';form.append(hint,challenge,status,send);dialog.append(form);document.body.append(dialog);dialog.onclose=()=>dialog.remove();form.onsubmit=async event=>{event.preventDefault();send.disabled=true;status.textContent='발송 요청 중입니다.';try{const turnstileToken=await window.G9STAR.challengeToken();const response=await fetch(window.G9STAR.apiBase+'/v1/admin/password-recovery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,turnstileToken})});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'발송 요청에 실패했습니다.');status.textContent=data.message;send.textContent='요청 완료';}catch(error){status.textContent=error.message;send.disabled=false;}};dialog.showModal();};
 document.querySelector('#adminLoginForm').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button[type="submit"]');button.disabled=true;try{const turnstileToken=await window.G9STAR.challengeToken();const response=await fetch(window.G9STAR.apiBase+'/v1/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({login:document.querySelector('#adminLogin').value,password:document.querySelector('#adminPassword').value,turnstileToken})});const body=await response.json();if(!response.ok)throw Error(body.error?.message||'로그인하지 못했습니다.');sessionStorage.setItem('g9star-admin-session',JSON.stringify(body));location.reload()}catch(error){message.textContent=error.message;button.disabled=false}};
})();
