(function(){
 const KEY='earthplayground-portal-v2',site=window.G9STAR;
 const session=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
 function save(data){if(!data.accessToken)throw Error('로그인 응답을 확인할 수 없습니다. 다시 시도하세요.');localStorage.setItem(KEY,JSON.stringify({member:data.member,token:data.accessToken,firstAttribution:data.member?.firstAttribution,currentAttribution:data.member?.currentAttribution,coupons:[],order:null,audit:[]}));}
 async function request(path,body){const token=session().token;if(!token)throw Error('회원 로그인 후 이용하세요.');const response=await fetch(site.apiBase+'/v1/member-auth/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store'});const data=await response.json();if(session().token!==token)throw Error('로그인 상태가 변경되었습니다. 다시 시도하세요.');if(!response.ok){if(response.status===401){localStorage.removeItem(KEY);window.dispatchEvent(new Event('g9star-member-session'));}const e=Error(data.error?.message||'요청에 실패했습니다.');e.code=data.error?.code;throw e;}return data;}
 function home(data){save(data);window.location.assign(new URL('/',window.location.href).href);}
 function eye(input){const wrap=document.createElement('span');wrap.className='password-input-wrap';input.parentNode.insertBefore(wrap,input);wrap.append(input);const button=document.createElement('button');button.type='button';button.className='password-visibility';button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>';button.setAttribute('aria-label','비밀번호 보기');button.onclick=()=>{input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'비밀번호 보기':'비밀번호 숨기기');button.setAttribute('aria-pressed',String(input.type==='text'));};wrap.append(button);}
 site.member={session,save,request,home,eye};
})();
