(function(){
 const $=s=>document.querySelector(s),KEY='earthplayground-portal-v2',API=window.G9STAR.apiBase,signup=$('#memberSignupForm'),login=$('#memberLoginForm'),change=$('#memberPasswordForm');let verifiedEmail='',verificationToken='';let navigating=false;
 function status(text,id='#memberAuthStatus'){$(id).textContent=text;}
 async function api(path,body,token){const response=await fetch(API+path,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'요청에 실패했습니다.');return data;}
 async function challenged(path,body){return api(path,{...body,turnstileToken:await window.G9STAR.challengeToken()});}
 function save(data){localStorage.setItem(KEY,JSON.stringify({member:data.member,token:data.accessToken,firstAttribution:data.member?.firstAttribution,currentAttribution:data.member?.currentAttribution,coupons:[],order:null,audit:[]}));}
 function goHome(data){status('완료되었습니다. 홈으로 이동합니다.');navigating=true;const link=document.createElement('a');link.href='/';link.textContent='홈으로 이동';$('#memberAuthStatus').append(link);window.G9STAR.member.home(data);}
 function eye(input){const wrap=document.createElement('span');wrap.className='password-input-wrap';input.parentNode.insertBefore(wrap,input);wrap.append(input);const b=document.createElement('button');b.type='button';b.className='password-visibility';b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>';b.setAttribute('aria-label','비밀번호 보기');b.setAttribute('aria-pressed','false');b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.setAttribute('aria-pressed',String(show));b.setAttribute('aria-label',show?'비밀번호 숨기기':'비밀번호 보기');};wrap.append(b);}
 document.querySelectorAll('.member-auth-form input[type="password"]').forEach(eye);
 async function run(button,action,id){button.disabled=true;try{await action();}catch(e){status(e.message,id);}finally{if(!navigating)button.disabled=false;}}
 if(signup){
  const linked=new URLSearchParams(location.search).get('ref');if(linked)$('#referralCode').value=linked.toUpperCase();
  $('#memberEmail').oninput=()=>{verifiedEmail='';verificationToken='';status('이메일 인증을 완료하세요.','#emailStatus');};
  $('#sendVerification').onclick=()=>run($('#sendVerification'),async()=>{const address=$('#memberEmail').value.trim().toLowerCase();if(!$('#memberEmail').reportValidity())return;const data=await challenged('/v1/member-auth/send-verification',{email:address});verifiedEmail='';verificationToken='';status(data.message,'#emailStatus');},'#emailStatus');
  $('#verifyEmail').onclick=()=>run($('#verifyEmail'),async()=>{const address=$('#memberEmail').value.trim().toLowerCase();const data=await challenged('/v1/member-auth/verify-email',{email:address,code:$('#emailCode').value.trim()});verifiedEmail=address;verificationToken=data.verificationToken;status('이메일 인증이 완료되었습니다.','#emailStatus');},'#emailStatus');
  $('#verifyReferral').onclick=()=>run($('#verifyReferral'),async()=>{const code=$('#referralCode').value.trim().toUpperCase();$('#referralCode').value=code;if(!code){status('추천인 코드 없이 가입할 수 있습니다.','#referralResult');return;}const ref=await api('/v1/referrals/validate',{code});status('유효한 추천인 코드입니다. '+(ref.partnerName||''),'#referralResult');},'#referralResult');
  signup.onsubmit=e=>{e.preventDefault();run(signup.querySelector('[type="submit"]'),async()=>{if(!verificationToken||verifiedEmail!==$('#memberEmail').value.trim().toLowerCase())throw Error('이메일 인증을 완료해 주세요.');if($('#memberPassword').value!==$('#memberPasswordConfirm').value)throw Error('비밀번호 확인이 일치하지 않습니다.');const data=await challenged('/v1/members',{email:verifiedEmail,verificationToken,password:$('#memberPassword').value,phone:$('#memberPhone').value,name:$('#memberName').value,directCode:$('#referralCode').value.trim().toUpperCase(),linkCode:undefined,privacyConsent:$('#privacyConsent').checked,termsConsent:$('#termsConsent').checked});goHome(data);});};
 }
 if(login){login.onsubmit=e=>{e.preventDefault();run(login.querySelector('[type="submit"]'),async()=>{const data=await challenged('/v1/member-auth/login',{email:$('#memberEmail').value,password:$('#memberPassword').value});if(data.mustChangePassword){save(data);window.location.assign('/mypage?tab=password');}else goHome(data);});};
  $('#memberRecovery').onclick=()=>run($('#memberRecovery'),async()=>{if(!$('#memberEmail').reportValidity())return;const data=await challenged('/v1/member-auth/password-recovery',{email:$('#memberEmail').value});status(data.message);});
  change.onsubmit=e=>{e.preventDefault();run(change.querySelector('[type="submit"]'),async()=>{if($('#newMemberPassword').value!==$('#confirmMemberPassword').value)throw Error('비밀번호 확인이 일치하지 않습니다.');let state;try{state=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{state={}}const data=await api('/v1/member-auth/password',{currentPassword:$('#temporaryPassword').value,newPassword:$('#newMemberPassword').value},state.token);goHome(data);},'#memberPasswordStatus');};
  // A recovered session remains restricted until the password is changed, even after reload.
  let state;try{state=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}if(state?.token)fetch(API+'/v1/member-auth/session',{headers:{authorization:'Bearer '+state.token},cache:'no-store'}).then(r=>r.ok?r.json():null).then(a=>{if(a){window.location.assign(a.mustChangePassword?'/mypage?tab=password':'/');}}).catch(()=>{});
 }
})();
