(async function(){
 const M=window.G9STAR.member,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>Number(n||0).toLocaleString('ko-KR')+'원';let data=null;
 const status=text=>$('#mypageStatus').textContent=text;
 const run=async(button,task)=>{button.disabled=true;try{await task();}catch(e){status(e.message);}finally{button.disabled=false;}};
 function show(tab){document.querySelectorAll('[data-tab]').forEach(s=>s.hidden=s.dataset.tab!==tab);document.querySelectorAll('.mypage-tabs a').forEach(a=>{if(new URL(a.href).searchParams.get('tab')===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
 const empty=text=>'<p class="empty-state">'+text+'</p>';
 function render(result){data=result;$('#profileEmail').value=data.profile.email;$('#profileName').value=data.profile.name;$('#profilePhone').value=data.profile.phone;
  $('#favoritesList').innerHTML=data.favorites.map(item=>`<article class="mypage-item"><div>${item.href?`<a href="${esc(item.href)}">${esc(item.name)}</a>`:esc(item.name)}<p>${item.type==='showcase'?'관심 공간':'상품 찜'}</p></div><button type="button" class="compact-button" data-remove-favorite="${esc(item.id)}" data-type="${esc(item.type)}">삭제</button></article>`).join('')||empty('찜한 상품이나 공간이 없습니다.');
  $('#cartList').innerHTML=data.cart.map(item=>`<article class="mypage-item"><div>${item.href?`<a href="${esc(item.href)}">${esc(item.name)}</a>`:esc(item.name)}<p>${item.price===null?'가격 확인 필요':money(item.price)} · ${esc(item.color)} ${esc(item.size)}</p></div><label>수량<input type="number" min="1" max="99" value="${item.quantity}" aria-label="${esc(item.name)} 수량" data-cart-quantity="${esc(item.id)}"></label><button class="compact-button" type="button" data-remove-cart="${esc(item.id)}">삭제</button></article>`).join('')||empty('장바구니가 비어 있습니다.');
  $('#cartTotal').textContent='상품 합계: '+money(data.cart.reduce((sum,c)=>sum+Number(c.price||0)*c.quantity,0))+' (배송·설치 별도)';const estimate=new URL('/estimate',location.origin);estimate.searchParams.set('cart',data.cart.map(c=>`${c.name} × ${c.quantity}`).join('\n').slice(0,2500));$('#cartEstimate').href=estimate.href;
  $('#mypageCoupons').innerHTML=data.coupons.map(c=>{const expired=c.status==='ISSUED'&&new Date(c.expiresAt)<=new Date();return `<article class="coupon-card"><div><strong>${esc(c.title||c.campaignCode)}</strong><p>${esc(expired?'만료':c.status)} · ${esc(new Date(c.expiresAt).toLocaleDateString('ko-KR'))}까지</p></div><b>${c.discountType==='PERCENT'?esc(c.discountValue)+'%':money(c.amount)}</b></article>`}).join('')||empty('보유한 쿠폰이 없습니다.');
  $('#notificationsList').innerHTML=data.notifications.map(n=>`<article class="mypage-item"><div><strong>${n.read?'읽음':'새 알림'}</strong><p>${esc(n.message)}</p><small>${esc(new Date(n.createdAt).toLocaleString('ko-KR'))}</small></div></article>`).join('')||empty('받은 알림이 없습니다.');
 }
 document.querySelectorAll('#mypagePasswordForm input').forEach(M.eye);
 $('#mypagePasswordForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{if($('#newPassword').value!==$('#confirmPassword').value)throw Error('새 비밀번호 확인이 일치하지 않습니다.');const account=await M.request('password',{currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value});M.save(account);window.location.assign('/mypage?tab=profile');});};
 $('#mypageProfileForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{render(await M.request('profile',{name:$('#profileName').value,phone:$('#profilePhone').value}));const state=M.session();state.member.name=data.profile.name;localStorage.setItem('earthplayground-portal-v2',JSON.stringify(state));status('내 정보를 저장했습니다.');});};
 $('#mypageCouponForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const token=M.session().token,r=await fetch(window.G9STAR.apiBase+'/v1/coupons/register',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({campaignCode:$('#couponCode').value.trim().toUpperCase()})}),body=await r.json();if(!r.ok)throw Error(body.error?.message||'쿠폰 등록에 실패했습니다.');render(await M.request('profile'));status('쿠폰을 등록했습니다.');});};
 $('#readNotifications').onclick=e=>run(e.currentTarget,async()=>{render(await M.request('notifications/read',{all:true}));status('알림을 읽음 처리했습니다.');});
 $('#mypageSearchForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const r=await fetch(window.G9STAR.apiBase+'/v1/products'),body=await r.json();if(!r.ok)throw Error('상품을 불러올 수 없습니다.');const q=$('#productSearch').value.trim().toLowerCase();$('#searchResults').innerHTML=body.items.filter(p=>(p.name+' '+p.code).toLowerCase().includes(q)).map(p=>`<article class="mypage-item"><a href="/product?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a><span>${money(p.salePrice)}</span></article>`).join('')||empty('검색 결과가 없습니다.');});};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-favorite],[data-remove-cart]');if(!b)return;run(b,async()=>{const favorite=b.dataset.removeFavorite;render(await M.request(favorite?'favorites':'cart',favorite?{id:favorite,type:b.dataset.type,remove:true}:{id:b.dataset.removeCart,remove:true}));status('삭제했습니다.');});});
 document.addEventListener('change',e=>{if(!e.target.matches('[data-cart-quantity]'))return;run(e.target,async()=>{render(await M.request('cart',{id:e.target.dataset.cartQuantity,quantity:Number(e.target.value)}));status('수량을 변경했습니다.');});});
 if(!M.session().token){window.location.replace('/login');return;}
 try{const account=await M.request('session');if(account.mustChangePassword){show('password');$('#passwordHint').textContent='임시 비밀번호로 로그인했습니다. 새 비밀번호로 변경하면 내 정보와 회원 기능을 이용할 수 있습니다.';document.querySelector('.mypage-tabs').hidden=true;status('새 비밀번호를 먼저 설정해 주세요.');return;}render(await M.request('profile'));const tab=new URLSearchParams(location.search).get('tab')||'profile';show(['profile','password','favorites','cart','coupons','notifications','search','support'].includes(tab)?tab:'profile');status('회원 정보가 준비되었습니다.');}catch(e){status(e.message);if(!M.session().token)window.location.replace('/login');}
})();
