(function(){
 const API=localStorage.getItem('earthplayground-api')||'http://127.0.0.1:4100',KEY='earthplayground-portal-v2',initial={member:null,firstAttribution:null,currentAttribution:null,coupons:[],order:null,audit:[]};
 const qs=s=>document.querySelector(s),normalize=value=>String(value||'').trim().toUpperCase(),load=()=>{try{return{...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...initial}}},save=state=>localStorage.setItem(KEY,JSON.stringify(state)),log=(state,action,detail)=>state.audit.unshift({action,detail,occurredAt:new Date().toISOString()});
 // PDF P-01 고객 상태 매핑: 서버 error.code → 상태 라벨/문구
 const REFERRAL_STATE={REFERRAL_NOT_FOUND:'존재하지 않는 추천코드입니다.',REFERRAL_SUSPENDED:'중지된 추천코드입니다. 파트너에 문의하세요.',REFERRAL_EXPIRED:'만료된 추천코드입니다.',VALIDATION_ERROR:'추천코드를 다시 입력해 주세요.'};
 const COUPON_STATE={COUPON_ALREADY_ISSUED:'이미 등록한 쿠폰입니다.',CAMPAIGN_NOT_FOUND:'존재하지 않는 쿠폰 코드입니다.',CAMPAIGN_SUSPENDED:'중지된 캠페인입니다.',CAMPAIGN_EXPIRED:'만료된 쿠폰입니다.',CAMPAIGN_NOT_STARTED:'아직 시작되지 않은 캠페인입니다.',CAMPAIGN_INVALID:'사용할 수 없는 캠페인입니다.',COUPON_MINIMUM_NOT_MET:'최소 주문금액을 충족하지 못했습니다.',COUPON_EXPIRED:'만료된 쿠폰입니다.',COUPON_NOT_OWNED:'본인 쿠폰이 아닙니다.',UNAUTHENTICATED:'로그인이 필요합니다. 다시 가입/로그인해 주세요.'};
 const stateMessage=(map,error)=>error.code&&map[error.code]?map[error.code]:(error.code?error.message:'네트워크 오류 · 잠시 후 다시 시도해 주세요.');
 async function api(path,options={},auth=false){const token=auth?load().token:null;let response;try{response=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{}),...(options.headers||{})}})}catch(networkError){const e=new Error('네트워크 오류');e.network=true;throw e}const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body.error?.message||`API ${response.status}`);error.code=body.error?.code;throw error}return body}
 const busy=(button,active,label)=>{button.disabled=active;if(active){button.dataset.label=button.textContent;button.textContent=label}else if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}};
 const setMessage=(element,text,error=false)=>{element.className='validation '+(error?'error':'success');element.textContent=text};
 function couponView(raw){return{id:raw.id,memberId:raw.memberId||raw.member_id,campaignCode:raw.campaignCode||raw.campaign_code||raw.code,title:raw.title||raw.campaignCode||raw.code||'회원 쿠폰',amount:Number(raw.amount??raw.amount_krw??0),minAmount:Number(raw.minAmount??raw.minimum_krw??0),discountType:raw.discountType||raw.discount_type||'FIXED',discountValue:Number(raw.discountValue??raw.discount_value??raw.amount??0),maxDiscount:raw.maxDiscount??raw.max_discount_krw,discountAmount:raw.discountAmount??raw.discount_amount,status:raw.status,expiresAt:raw.expiresAt||raw.expires_at,reservationId:raw.reservationId||raw.reservation_id}}
 const discountFor=(coupon,subtotal)=>coupon?.discountType==='PERCENT'?Math.min(Math.floor(subtotal*coupon.discountValue/100),Number(coupon.maxDiscount||Number.MAX_SAFE_INTEGER)):Number(coupon?.amount||0);
 function signup(){
  const nameInput=qs('.form-grid label:nth-child(3) input');if(nameInput&&!nameInput.id)nameInput.id='memberName';
  const input=qs('#referralCode'),result=qs('#referralResult'),complete=qs('#completeSignup'),verify=qs('#verifyReferral'),linked=new URLSearchParams(location.search).get('ref');let verified=null;if(linked)input.value=normalize(linked);
  verify.onclick=async()=>{const code=normalize(input.value);input.value=code;verified=null;busy(verify,true,'확인 중');try{const ref=await api('/v1/referrals/validate',{method:'POST',body:JSON.stringify({code})});verified={code:ref.code,partnerId:ref.partnerId||ref.partner_id,partnerName:ref.partnerName||ref.partner_name,ownerId:ref.ownerId||ref.owner_code};setMessage(result,`유효 · ${verified.partnerName} / ${verified.ownerId} 담당자`)}catch(error){setMessage(result,stateMessage(REFERRAL_STATE,error),true)}finally{busy(verify,false)}};
  complete.onclick=async()=>{const box=qs('#signupResult');if(!verified)return setMessage(result,'가입 전 유효한 추천인 코드를 확인해 주세요.',true);if(!qs('#attributionConsent').checked)return setMessage(result,'귀속 정보 처리 동의가 필요합니다.',true);busy(complete,true,'가입 처리 중');try{const member=await api('/v1/members',{method:'POST',body:JSON.stringify({name:qs('#memberName').value.trim(),linkCode:linked||undefined,directCode:verified.code})}),state=load();state.member={id:member.id,name:member.name};state.token=member.accessToken||null;state.firstAttribution=member.firstAttribution;state.currentAttribution=member.currentAttribution;state.coupons=[];state.order=null;log(state,'MEMBER_SIGNUP',{memberId:member.id,finalCode:verified.code});save(state);box.hidden=false;box.innerHTML=`<strong>가입이 완료되었습니다.</strong><p>회원 ${member.id} · 최초 귀속 ${verified.code}</p><a class="compact-button dark" href="coupons.html">쿠폰 등록하기</a>`}catch(error){setMessage(result,stateMessage(REFERRAL_STATE,error),true)}finally{busy(complete,false)}}
 }
 function card(coupon){const expires=coupon.expiresAt?new Date(coupon.expiresAt).toLocaleDateString('ko-KR'):'-',benefit=coupon.discountType==='PERCENT'?`${coupon.discountValue}%${coupon.maxDiscount?` · 최대 ${Number(coupon.maxDiscount).toLocaleString()}원`:''}`:`${coupon.amount.toLocaleString()}원`;return`<article class="coupon-card ${String(coupon.status).toLowerCase()}"><div><span>${coupon.status}</span><strong>${coupon.title}</strong><p>상품 ${coupon.minAmount.toLocaleString()}원 이상 · 구매 적용</p><small>${expires}까지</small></div><b>${benefit}</b></article>`}
 function coupons(){const list=qs('#couponList'),message=qs('#couponMessage'),button=qs('#registerCoupon');let state=load();const render=()=>{list.innerHTML=state.coupons.length?state.coupons.map(card).join(''):'<div class="empty-state">등록된 쿠폰이 없습니다.</div>';qs('#couponCount').textContent=state.coupons.filter(c=>c.status==='ISSUED').length+'개'};button.onclick=async()=>{if(!state.member)return setMessage(message,'먼저 사업자 회원가입을 완료해 주세요.',true);const campaignCode=normalize(qs('#campaignCode').value);busy(button,true,'등록 중');try{const issued=couponView(await api('/v1/coupons/register',{method:'POST',body:JSON.stringify({campaignCode})},true));state=load();state.coupons.unshift(issued);log(state,'MEMBER_COUPON_ISSUED',{couponId:issued.id,campaignCode,attributionChanged:false});save(state);setMessage(message,'회원 전용 쿠폰이 발급되었습니다. 추천인 귀속은 유지됩니다.');render()}catch(error){setMessage(message,stateMessage(COUPON_STATE,error),true)}finally{busy(button,false)}};render()}
 function checkout(){
  let state=load(),selected=null;const options=qs('#checkoutCoupons'),message=qs('#checkoutMessage'),pay=qs('#payButton'),paymentState=qs('#paymentState'),cancel=qs('#cancelOrder'),reservationId=()=>`checkout:${state.member?.id||'guest'}:${Date.now()}`;
  const render=()=>{const issued=state.coupons.filter(c=>c.status==='ISSUED');options.innerHTML='<label class="coupon-option"><input type="radio" name="coupon" value="">쿠폰 사용 안 함</label>'+issued.map(c=>{const discount=discountFor(c,780000);return`<label class="coupon-option recommended"><input type="radio" name="coupon" value="${c.id}"><span><strong>${c.title}</strong><small>${c.minAmount.toLocaleString()}원 이상 · 직접 선택</small></span><b>-${discount.toLocaleString()}원</b></label>`}).join('');options.querySelectorAll('input').forEach(input=>input.onchange=()=>{selected=state.coupons.find(c=>c.id===input.value)||null;const discount=discountFor(selected,780000);qs('#discountValue').textContent='- '+discount.toLocaleString()+'원';qs('#totalValue').textContent=(840000-discount).toLocaleString()+'원';pay.textContent=(840000-discount).toLocaleString()+'원 결제하기';setMessage(message,selected?'결제 시 서버에서 쿠폰을 원자적으로 예약합니다.':'쿠폰을 사용하지 않습니다.')})};
  async function reserve(){if(!selected)return null;if(!state.member)throw new Error('회원 정보가 없습니다.');const id=reservationId(),updated=await api(`/v1/coupons/${selected.id}/reserve`,{method:'POST',body:JSON.stringify({eligibleSubtotal:780000,reservationId:id})},true);selected={...selected,...couponView(updated),amount:Number(updated.discountAmount??updated.discount_amount??discountFor(selected,780000)),reservationId:id,status:'RESERVED'};state.coupons=state.coupons.map(c=>c.id===selected.id?selected:c);log(state,'COUPON_RESERVED',{couponId:selected.id,reservationId:id,discountAmount:selected.amount});save(state);paymentState.textContent='RESERVED · 결제 결과 대기';return id}
  const resetSelection=()=>{selected=null;qs('#discountValue').textContent='- 0원';qs('#totalValue').textContent='840,000원';busy(pay,false);pay.textContent='840,000원 결제하기';render()};
  async function finish(success){busy(pay,true,'처리 중');try{const id=await reserve();if(selected&&id){const updated=await api(`/v1/coupons/${selected.id}/complete`,{method:'POST',body:JSON.stringify({reservationId:id,success})},true);selected={...selected,status:updated.status||(success?'USED':'ISSUED'),reservationId:undefined};state.coupons=state.coupons.map(c=>c.id===selected.id?selected:c)}if(success){state.order={id:`O-${Date.now()}`,status:'PAID',couponId:selected?.id||null,discount:selected?.amount||0};log(state,'ORDER_PAID',{orderId:state.order.id,couponId:state.order.couponId});paymentState.textContent='결제 완료 · 쿠폰 '+(selected?'USED':'미사용');cancel.hidden=false;pay.disabled=true}else{log(state,'PAYMENT_FAILED_COUPON_RELEASED',{couponId:selected?.id||null});paymentState.textContent='결제 실패 · 쿠폰 ISSUED 복구';resetSelection()}save(state)}catch(error){setMessage(message,stateMessage(COUPON_STATE,error),true);busy(pay,false)}}
  pay.onclick=()=>finish(true);qs('#failPayment').onclick=()=>finish(false);cancel.onclick=async()=>{if(!state.order)return;busy(cancel,true,'복원 중');try{if(state.order.couponId){const existing=state.coupons.find(c=>c.id===state.order.couponId),updated=await api(`/v1/coupons/${state.order.couponId}/restore-full-cancellation`,{method:'POST',body:JSON.stringify({orderId:state.order.id})},true),restored={...existing,status:updated.status||'ISSUED',reservationId:undefined};state.coupons=state.coupons.map(c=>c.id===restored.id?restored:c)}state.order.status='CANCELLED';log(state,'ORDER_CANCELLED_COUPON_RESTORED',{orderId:state.order.id});save(state);paymentState.textContent='전액 취소 · 유효 쿠폰 ISSUED 복원';cancel.hidden=true;resetSelection()}catch(error){setMessage(message,stateMessage(COUPON_STATE,error),true)}finally{busy(cancel,false)}};render()
 }
 const page=document.body.dataset.page;if(page==='signup')signup();if(page==='coupons')coupons();if(page==='checkout')checkout();
})();
