(function(){
 const API=window.G9STAR.apiBase,KEY='earthplayground-portal-v2',initial={member:null,firstAttribution:null,currentAttribution:null,coupons:[],order:null,audit:[]};
 const qs=s=>document.querySelector(s),normalize=value=>String(value||'').trim().toUpperCase(),load=()=>{try{return{...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...initial}}},save=state=>localStorage.setItem(KEY,JSON.stringify(state)),log=(state,action,detail)=>state.audit.unshift({action,detail,occurredAt:new Date().toISOString()});
 // PDF P-01 고객 상태 매핑: 서버 error.code → 상태 라벨/문구
 const REFERRAL_STATE={REFERRAL_NOT_FOUND:'존재하지 않는 추천코드입니다.',REFERRAL_SUSPENDED:'중지된 추천코드입니다. 파트너에 문의하세요.',REFERRAL_EXPIRED:'만료된 추천코드입니다.',VALIDATION_ERROR:'추천코드를 다시 입력해 주세요.'};
 const COUPON_STATE={COUPON_ALREADY_ISSUED:'이미 등록한 쿠폰입니다.',CAMPAIGN_NOT_FOUND:'존재하지 않는 쿠폰 코드입니다.',CAMPAIGN_SUSPENDED:'중지된 캠페인입니다.',CAMPAIGN_EXPIRED:'만료된 쿠폰입니다.',CAMPAIGN_NOT_STARTED:'아직 시작되지 않은 캠페인입니다.',CAMPAIGN_INVALID:'사용할 수 없는 캠페인입니다.',COUPON_MINIMUM_NOT_MET:'최소 주문금액을 충족하지 못했습니다.',COUPON_EXPIRED:'만료된 쿠폰입니다.',COUPON_NOT_OWNED:'본인 쿠폰이 아닙니다.',UNAUTHENTICATED:'로그인이 필요합니다. 다시 가입/로그인해 주세요.'};
 const stateMessage=(map,error)=>error.code&&map[error.code]?map[error.code]:(error.code?error.message:'네트워크 오류 · 잠시 후 다시 시도해 주세요.');
 async function api(path,options={},auth=false){const token=auth?load().token:null;let response;try{response=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{}),...(options.headers||{})}})}catch(networkError){const e=new Error('네트워크 오류');e.network=true;throw e}const body=await response.json().catch(()=>({}));if(auth&&load().token!==token){const error=new Error('로그인 상태가 변경되었습니다. 다시 시도해 주세요.');error.code='SESSION_CHANGED';throw error}if(!response.ok){if(auth&&response.status===401){localStorage.removeItem(KEY);window.dispatchEvent(new Event('g9star-member-session'));}const error=new Error(body.error?.message||`API ${response.status}`);error.code=body.error?.code;throw error}return body}
 const busy=(button,active,label)=>{button.disabled=active;if(active){button.dataset.label=button.textContent;button.textContent=label}else if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}};
 const setMessage=(element,text,error=false)=>{element.className='validation '+(error?'error':'success');element.textContent=text};
 function couponView(raw){return{id:raw.id,memberId:raw.memberId||raw.member_id,campaignCode:raw.campaignCode||raw.campaign_code||raw.code,title:raw.title||raw.campaignCode||raw.code||'회원 쿠폰',amount:Number(raw.amount??raw.amount_krw??0),minAmount:Number(raw.minAmount??raw.minimum_krw??0),discountType:raw.discountType||raw.discount_type||'FIXED',discountValue:Number(raw.discountValue??raw.discount_value??raw.amount??0),maxDiscount:raw.maxDiscount??raw.max_discount_krw,discountAmount:raw.discountAmount??raw.discount_amount,status:raw.status==='ISSUED'&&new Date(raw.expiresAt||raw.expires_at).getTime()<=Date.now()?'EXPIRED':raw.status,expiresAt:raw.expiresAt||raw.expires_at,reservationId:raw.reservationId||raw.reservation_id}}
 const discountFor=(coupon,subtotal)=>coupon?.discountType==='PERCENT'?Math.min(Math.floor(subtotal*coupon.discountValue/100),Number(coupon.maxDiscount||Number.MAX_SAFE_INTEGER)):Number(coupon?.amount||0);
 const escapeText=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function card(coupon){const expires=coupon.expiresAt?new Date(coupon.expiresAt).toLocaleDateString('ko-KR'):'-',benefit=coupon.discountType==='PERCENT'?`${coupon.discountValue}%${coupon.maxDiscount?` · 최대 ${Number(coupon.maxDiscount).toLocaleString()}원`:''}`:`${coupon.amount.toLocaleString()}원`;return`<article class="coupon-card ${String(coupon.status).toLowerCase()}"><div><span>${coupon.status}</span><strong>${escapeText(coupon.title)}</strong><p>상품 ${coupon.minAmount.toLocaleString()}원 이상 · 구매 적용</p><small>${expires}까지</small></div><b>${benefit}</b></article>`}
 function coupons(){const list=qs('#couponList'),message=qs('#couponMessage'),button=qs('#registerCoupon');let state=load();state.coupons=state.coupons.map(couponView);const render=()=>{list.innerHTML=state.coupons.length?state.coupons.map(card).join(''):'<div class="empty-state">등록된 쿠폰이 없습니다.</div>';qs('#couponCount').textContent=state.coupons.filter(c=>c.status==='ISSUED').length+'개'};button.onclick=async()=>{state=load();if(!state.member||!state.token)return setMessage(message,'회원 로그인 후 이용해 주세요.',true);const campaignCode=normalize(qs('#campaignCode').value);busy(button,true,'등록 중');try{const issued=couponView(await api('/v1/coupons/register',{method:'POST',body:JSON.stringify({campaignCode})},true));state=load();state.coupons.unshift(issued);log(state,'MEMBER_COUPON_ISSUED',{couponId:issued.id,campaignCode,attributionChanged:false});save(state);setMessage(message,'회원 전용 쿠폰이 발급되었습니다. 추천인 귀속은 유지됩니다.');render()}catch(error){setMessage(message,stateMessage(COUPON_STATE,error),true)}finally{busy(button,false)}};render();if(state.token)api('/v1/me',{},true).then(body=>{state=load();state.member=body.member;state.coupons=body.coupons.map(couponView);save(state);render()}).catch(error=>{state=load();state.coupons=state.coupons.map(couponView);render();setMessage(message,stateMessage(COUPON_STATE,error),true)})}
 const page=document.body.dataset.page;if(page==='coupons')coupons();// 결제는 공개 베타에서 실행하지 않습니다.

})();
